import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  mainScroll: {
    flex: 1,
  },

  // =========================================================================
  // HOME SCREEN STYLES (Screenshot 1)
  // =========================================================================
  homeHeader: {
    backgroundColor: '#131d2e',
    paddingTop: 18,
    paddingBottom: 18,
    paddingHorizontal: 16,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  homeHeaderTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  homeHeaderGreeting: {
    fontSize: 13,
    color: '#94a3b8',
    fontWeight: '500',
  },
  homeHeaderBrand: {
    fontSize: 22,
    fontWeight: '800',
    color: '#ffffff',
    letterSpacing: -0.4,
  },
  bellBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#1e293b',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  bellBadgeDot: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 9,
    height: 9,
    borderRadius: 4.5,
    backgroundColor: '#f97316',
  },
  homeSearchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1e293b',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#334155',
  },
  homeSearchInput: {
    flex: 1,
    fontSize: 13.5,
    color: '#ffffff',
  },
  heroBanner: {
    height: 140,
    borderRadius: 18,
    backgroundColor: '#ea580c',
    justifyContent: 'space-between',
    padding: 16,
    overflow: 'hidden',
    marginBottom: 18,
    shadowColor: '#ea580c',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 4,
  },
  heroOverlay: {
    flex: 1,
    justifyContent: 'center',
  },
  heroHeadline: {
    fontSize: 18,
    fontWeight: '900',
    color: '#ffffff',
    letterSpacing: -0.3,
  },
  heroSubheadline: {
    fontSize: 12.5,
    color: '#fed7aa',
    marginTop: 4,
    fontWeight: '600',
  },
  heroDotsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-end',
    gap: 5,
  },
  heroPillActive: {
    width: 18,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#ffffff',
  },
  heroDot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
  },
  sectionTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionHeaderTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0f172a',
    letterSpacing: -0.2,
  },
  seeAllOrangeLink: {
    fontSize: 13,
    fontWeight: '700',
    color: '#f97316',
  },
  categoryGrid4x2: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 20,
    gap: 8,
  },
  categoryCardItem: {
    width: (width - 32 - 24) / 4,
    backgroundColor: '#ffffff',
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#f1f5f9',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
  },
  categoryIconBadge: {
    width: 44,
    height: 44,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
  },
  categoryCardLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#334155',
    textAlign: 'center',
  },
  featuredProductGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 12,
  },
  featuredCard: {
    width: (width - 32 - 12) / 2,
    backgroundColor: '#ffffff',
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
    marginBottom: 12,
  },
  featuredThumbBox: {
    height: 120,
    backgroundColor: '#f8fafc',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  discountTagBadge: {
    position: 'absolute',
    top: 8,
    left: 8,
    backgroundColor: '#f97316',
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 6,
  },
  discountTagText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '800',
  },
  heartBtn: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  featuredCardBody: {
    padding: 10,
  },
  featuredBrandName: {
    fontSize: 11,
    color: '#94a3b8',
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  featuredProductName: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#0f172a',
    marginTop: 2,
    height: 34,
  },
  featuredRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 4,
  },
  featuredPriceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 4,
  },
  featuredProductPrice: {
    fontSize: 15,
    fontWeight: '900',
    color: '#0f172a',
  },
  featuredAddBtn: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: '#f97316',
    justifyContent: 'center',
    alignItems: 'center',
  },
  featuredAddBtnText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '900',
  },

  // =========================================================================
  // CATEGORIES SCREEN STYLES (Screenshot 2)
  // =========================================================================
  categoriesHeader: {
    backgroundColor: '#131d2e',
    paddingTop: 24,
    paddingBottom: 20,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    marginBottom: 10,
  },
  categoriesHeaderTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#ffffff',
    letterSpacing: -0.3,
  },
  categoriesHeaderSubtitle: {
    fontSize: 13,
    color: '#94a3b8',
    marginTop: 4,
  },
  categoryRowCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 1,
  },
  categoryRowIconBox: {
    width: 52,
    height: 52,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  categoryRowTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#0f172a',
  },
  categoryRowCount: {
    fontSize: 12.5,
    color: '#64748b',
    marginTop: 2,
  },
  categoryRowChevron: {
    fontSize: 20,
    color: '#cbd5e1',
    fontWeight: '700',
  },

  // =========================================================================
  // CART SCREEN STYLES (Screenshot 3)
  // =========================================================================
  cartTopHeader: {
    backgroundColor: '#ffffff',
    paddingVertical: 18,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderColor: '#e2e8f0',
  },
  cartTopTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#0f172a',
  },
  cartEmptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 80,
    paddingHorizontal: 30,
  },
  cartEmptyIconCircle: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#f1f5f9',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  cartEmptyTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#0f172a',
    marginBottom: 6,
  },
  cartEmptySubtitle: {
    fontSize: 13.5,
    color: '#64748b',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 24,
  },
  startShoppingBtn: {
    backgroundColor: '#f97316',
    paddingHorizontal: 32,
    paddingVertical: 14,
    borderRadius: 14,
    shadowColor: '#f97316',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 4,
  },
  startShoppingBtnText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '800',
  },
  cartItemCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 14,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  cartQtyControls: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f1f5f9',
    borderRadius: 8,
    padding: 3,
  },
  qtyBtn: {
    width: 28,
    height: 28,
    backgroundColor: '#ffffff',
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  qtyBtnText: {
    fontWeight: '800',
    fontSize: 14,
    color: '#0f172a',
  },
  qtyValueText: {
    marginHorizontal: 10,
    fontWeight: '800',
    fontSize: 13,
  },
  voucherBox: {
    flexDirection: 'row',
    marginVertical: 12,
    gap: 8,
  },
  voucherInput: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    paddingHorizontal: 14,
    fontSize: 13,
  },
  voucherBtn: {
    backgroundColor: '#0f172a',
    paddingHorizontal: 18,
    borderRadius: 12,
    justifyContent: 'center',
  },
  voucherBtnText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 13,
  },
  payOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 12,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
    backgroundColor: '#ffffff',
    marginBottom: 8,
  },
  payOptionActive: {
    borderColor: '#f97316',
    backgroundColor: '#fff7ed',
  },
  summaryCard: {
    backgroundColor: '#ffffff',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    marginVertical: 12,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 3,
  },
  summaryLabel: {
    fontSize: 13,
    color: '#64748b',
  },
  summaryVal: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0f172a',
  },

  // =========================================================================
  // ORDERS SCREEN STYLES (Screenshot 4)
  // =========================================================================
  ordersTopHeader: {
    backgroundColor: '#131d2e',
    paddingTop: 24,
    paddingBottom: 16,
    paddingHorizontal: 20,
  },
  ordersTopTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#ffffff',
  },
  ordersTopSubtitle: {
    fontSize: 13,
    color: '#94a3b8',
    marginTop: 2,
  },
  ordersFilterBar: {
    flexDirection: 'row',
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderColor: '#e2e8f0',
  },
  ordersFilterTab: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    position: 'relative',
  },
  ordersFilterTabActive: {},
  ordersFilterTabText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#64748b',
  },
  ordersFilterTabTextActive: {
    color: '#f97316',
    fontWeight: '800',
  },
  ordersActiveIndicator: {
    position: 'absolute',
    bottom: 0,
    left: 8,
    right: 8,
    height: 3,
    backgroundColor: '#f97316',
    borderRadius: 2,
  },
  ordersEmptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 80,
    paddingHorizontal: 30,
  },
  ordersEmptyIconCircle: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: '#f1f5f9',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  ordersEmptyTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0f172a',
    marginBottom: 4,
  },
  ordersEmptySubtitle: {
    fontSize: 13,
    color: '#64748b',
    textAlign: 'center',
    marginBottom: 20,
  },
  orderCard: {
    backgroundColor: '#ffffff',
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  orderHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderColor: '#f1f5f9',
  },
  orderFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderColor: '#f1f5f9',
    paddingTop: 8,
    marginTop: 8,
  },
  trackBtn: {
    backgroundColor: '#0f172a',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  trackBtnText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '700',
  },

  // =========================================================================
  // PROFILE SCREEN STYLES (Screenshot 5)
  // =========================================================================
  profileTopHeader: {
    backgroundColor: '#131d2e',
    paddingTop: 24,
    paddingBottom: 24,
    paddingHorizontal: 18,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  profileUserRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  profileAvatarBox: {
    width: 60,
    height: 60,
    borderRadius: 18,
    backgroundColor: '#f97316',
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileAvatarText: {
    fontSize: 28,
    fontWeight: '900',
    color: '#ffffff',
  },
  profileUserName: {
    fontSize: 18,
    fontWeight: '800',
    color: '#ffffff',
    letterSpacing: -0.3,
  },
  profileUserEmail: {
    fontSize: 12.5,
    color: '#94a3b8',
    marginTop: 2,
  },
  profileUserPhone: {
    fontSize: 12,
    color: '#cbd5e1',
    marginTop: 2,
  },
  profileGearBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#1e293b',
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileStatsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  profileStatCard: {
    flex: 1,
    backgroundColor: '#1e293b',
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: 'center',
  },
  profileStatValue: {
    fontSize: 18,
    fontWeight: '900',
    color: '#ffffff',
  },
  profileStatLabel: {
    fontSize: 11,
    color: '#94a3b8',
    marginTop: 2,
    fontWeight: '600',
  },
  profileSectionEyebrow: {
    fontSize: 11.5,
    fontWeight: '800',
    color: '#64748b',
    letterSpacing: 0.5,
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  profileGroupCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    overflow: 'hidden',
  },
  profileRowItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderColor: '#f1f5f9',
  },
  profileRowLabel: {
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
    color: '#0f172a',
  },
  profileNotifBadge: {
    backgroundColor: '#f97316',
    borderRadius: 10,
    paddingHorizontal: 7,
    paddingVertical: 2,
    marginRight: 6,
  },
  profileNotifBadgeText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '800',
  },
  profileRowChevron: {
    fontSize: 18,
    color: '#cbd5e1',
    fontWeight: '700',
  },
  profileSignOutBtn: {
    marginTop: 20,
    backgroundColor: '#fef2f2',
    borderWidth: 1.5,
    borderColor: '#fecaca',
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  profileSignOutText: {
    color: '#dc2626',
    fontSize: 14,
    fontWeight: '800',
  },

  // =========================================================================
  // BOTTOM NAVIGATION BAR
  // =========================================================================
  bottomNav: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 64,
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderColor: '#e2e8f0',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  navItem: {
    alignItems: 'center',
    position: 'relative',
  },
  navText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#64748b',
    marginTop: 2,
  },
  navTextActive: {
    color: '#f97316',
  },
  navBadge: {
    position: 'absolute',
    top: -3,
    right: -6,
    backgroundColor: '#f97316',
    borderRadius: 8,
    minWidth: 16,
    height: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  navBadgeText: {
    color: '#ffffff',
    fontSize: 9,
    fontWeight: '800',
  },

  // =========================================================================
  // MODAL SHARED STYLES
  // =========================================================================
  modalNav: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderColor: '#f1f5f9',
    marginBottom: 10,
  },
  detailThumb: {
    height: 160,
    backgroundColor: '#f8fafc',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 10,
  },
  driverCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1e293b',
    borderRadius: 14,
    padding: 14,
  },

  // =========================================================================
  // SPLASH SCREEN STYLES
  // =========================================================================
  splashContainer: {
    flex: 1,
    backgroundColor: '#0d131f',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 50,
    paddingHorizontal: 24,
  },
  splashOrbTop: {
    position: 'absolute',
    top: -80,
    right: -80,
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: 'rgba(249, 115, 22, 0.08)',
  },
  splashOrbBottom: {
    position: 'absolute',
    bottom: -100,
    left: -100,
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: 'rgba(234, 88, 12, 0.12)',
  },
  splashCenter: {
    alignItems: 'center',
    marginTop: 180,
  },
  splashLogoBox: {
    width: 72,
    height: 72,
    borderRadius: 20,
    backgroundColor: '#f97316',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#f97316',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.45,
    shadowRadius: 18,
    elevation: 10,
    marginBottom: 20,
  },
  splashLogoText: {
    fontSize: 24,
    fontWeight: '900',
    color: '#ffffff',
    letterSpacing: 0.5,
  },
  splashTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: '#ffffff',
    letterSpacing: -0.5,
  },
  splashSubtitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#f97316',
    marginTop: 4,
    letterSpacing: 0.2,
  },
  splashTagline: {
    fontSize: 13.5,
    color: '#94a3b8',
    textAlign: 'center',
    marginTop: 20,
    lineHeight: 20,
    maxWidth: 260,
  },
  splashFooter: {
    alignItems: 'center',
    marginBottom: 20,
  },
  splashLoadingText: {
    fontSize: 12,
    color: '#94a3b8',
    marginTop: 10,
    fontWeight: '600',
  },

  // =========================================================================
  // ONBOARDING STYLES
  // =========================================================================
  onboardingContainer: {
    flex: 1,
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingVertical: 20,
  },
  onboardingHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
  },
  skipBtn: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    paddingHorizontal: 16,
    paddingVertical: 7,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  skipBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#475569',
  },
  onboardingBody: {
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  onboardingIconCircle: {
    width: 170,
    height: 170,
    borderRadius: 85,
    backgroundColor: '#ffffff',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 6,
    marginBottom: 36,
  },
  onboardingTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#0f172a',
    textAlign: 'center',
    marginBottom: 12,
    letterSpacing: -0.4,
  },
  onboardingDesc: {
    fontSize: 14,
    color: '#475569',
    textAlign: 'center',
    lineHeight: 22,
    maxWidth: 300,
  },
  onboardingFooter: {
    marginBottom: 24,
  },
  dotsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    marginBottom: 24,
  },
  dot: {
    height: 8,
    borderRadius: 4,
  },
  activeDot: {
    width: 24,
  },
  inactiveDot: {
    width: 8,
    backgroundColor: '#cbd5e1',
  },
  primaryAuthBtn: {
    backgroundColor: '#f97316',
    height: 52,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#f97316',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 4,
  },
  primaryAuthBtnText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '800',
  },
  secondaryAuthBtn: {
    backgroundColor: '#ffffff',
    height: 52,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#f97316',
    justifyContent: 'center',
    alignItems: 'center',
  },
  secondaryAuthBtnText: {
    color: '#f97316',
    fontSize: 15,
    fontWeight: '800',
  },

  // =========================================================================
  // AUTH / SIGN IN & SIGN UP STYLES
  // =========================================================================
  authContainer: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  authTopHeader: {
    backgroundColor: '#131d2e',
    paddingTop: 36,
    paddingBottom: 28,
    paddingHorizontal: 24,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
  },
  authMiniBrand: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 20,
  },
  authMiniLogoBox: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: '#f97316',
    justifyContent: 'center',
    alignItems: 'center',
  },
  authMiniLogoText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '900',
  },
  authMiniTitle: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '800',
  },
  authMiniSubtitle: {
    color: '#f97316',
    fontSize: 10,
    fontWeight: '700',
  },
  authHeroTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: '#ffffff',
    letterSpacing: -0.5,
  },
  authHeroSubtitle: {
    fontSize: 13.5,
    color: '#94a3b8',
    marginTop: 4,
  },
  authFormCard: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 24,
  },
  authFieldGroup: {
    marginBottom: 16,
  },
  authFieldLabel: {
    fontSize: 13.5,
    fontWeight: '700',
    color: '#0f172a',
    marginBottom: 8,
  },
  authInput: {
    backgroundColor: '#ffffff',
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    color: '#0f172a',
  },
  authPasswordInputBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    paddingRight: 12,
  },
  eyeBtn: {
    padding: 6,
  },
  authOptionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 4,
    marginBottom: 24,
  },
  rememberMeBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: '#cbd5e1',
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: {
    backgroundColor: '#f97316',
    borderColor: '#f97316',
  },
  checkmark: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '900',
  },
  rememberMeText: {
    fontSize: 13,
    color: '#475569',
    fontWeight: '600',
  },
  forgotPasswordText: {
    fontSize: 13,
    color: '#f97316',
    fontWeight: '700',
  },
  authFooterRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 30,
  },
  authFooterText: {
    fontSize: 13.5,
    color: '#64748b',
    fontWeight: '500',
  },
  authFooterLink: {
    fontSize: 13.5,
    color: '#f97316',
    fontWeight: '800',
  },
  toast: {
    position: 'absolute',
    top: 50,
    alignSelf: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.95)',
    paddingHorizontal: 18,
    paddingVertical: 8,
    borderRadius: 20,
    zIndex: 9999,
  },
  toastText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '700',
  },
});
