import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');

export const COLORS = {
  primary: '#f97316',       // Vibrant JEM Orange
  primaryDark: '#ea580c',   // Deep Orange
  primaryLight: '#fff7ed',  // Soft Warm Tint
  primaryBorder: '#fed7aa', // Warm Border
  
  navyDark: '#0d131f',      // Ultra Dark Navy
  navy: '#131d2e',          // Slate Dark Navy Header
  navyCard: '#1e293b',      // Dark Surface Navy
  navyMuted: '#334155',     // Subdued Navy Slate

  bgPage: '#f8fafc',        // Modern soft slate canvas
  surface: '#ffffff',       // Pure white card background
  surfaceSubtle: '#f1f5f9', // Light gray divider/bg
  
  textMain: '#0f172a',      // High contrast heading
  textBody: '#334155',      // Body text
  textMuted: '#64748b',     // Subtitle text
  textLight: '#94a3b8',     // Placeholders / captions
  
  border: '#e2e8f0',        // Clean border
  borderLight: '#f1f5f9',   // Subtle border
  
  success: '#10b981',       // Emerald green for stock & completed
  successBg: '#ecfdf5',
  successBorder: '#a7f3d0',
  
  warning: '#f59e0b',       // Amber warning
  warningBg: '#fffbeb',
  
  danger: '#ef4444',        // Red for errors & delete
  dangerBg: '#fef2f2',
  dangerBorder: '#fecaca',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.bgPage,
  },
  mainScroll: {
    flex: 1,
  },

  // =========================================================================
  // 1. HOME SCREEN STYLES
  // =========================================================================
  homeHeader: {
    backgroundColor: COLORS.navy,
    paddingTop: Platform.OS === 'ios' ? 20 : 16,
    paddingBottom: 20,
    paddingHorizontal: 18,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    shadowColor: COLORS.navyDark,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  homeHeaderTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  homeHeaderGreetingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  homeHeaderAvatarBox: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 3,
  },
  homeHeaderGreeting: {
    fontSize: 12,
    color: '#94a3b8',
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  homeHeaderBrand: {
    fontSize: 20,
    fontWeight: '900',
    color: '#ffffff',
    letterSpacing: -0.4,
  },
  homeHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  bellBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: COLORS.navyCard,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.navyMuted,
    position: 'relative',
  },
  bellBadgeDot: {
    position: 'absolute',
    top: 7,
    right: 7,
    width: 9,
    height: 9,
    borderRadius: 4.5,
    backgroundColor: COLORS.primary,
    borderWidth: 1.5,
    borderColor: COLORS.navy,
  },
  homeSearchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.navyCard,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === 'ios' ? 12 : 8,
    borderWidth: 1,
    borderColor: COLORS.navyMuted,
  },
  homeSearchInput: {
    flex: 1,
    fontSize: 14,
    color: '#ffffff',
    paddingVertical: 0,
  },
  homeSearchClear: {
    padding: 4,
  },
  
  // Hero Promo Carousel
  heroBanner: {
    minHeight: 144,
    borderRadius: 20,
    backgroundColor: COLORS.primaryDark,
    justifyContent: 'space-between',
    padding: 18,
    overflow: 'hidden',
    marginBottom: 20,
    shadowColor: COLORS.primaryDark,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.28,
    shadowRadius: 14,
    elevation: 6,
    position: 'relative',
  },
  heroBannerDeco1: {
    position: 'absolute',
    right: -20,
    bottom: -20,
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
  },
  heroBannerDeco2: {
    position: 'absolute',
    right: 40,
    top: -30,
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  heroBadgeTag: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    marginBottom: 8,
  },
  heroBadgeTagText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  heroHeadline: {
    fontSize: 19,
    fontWeight: '900',
    color: '#ffffff',
    letterSpacing: -0.3,
    lineHeight: 24,
  },
  heroSubheadline: {
    fontSize: 12.5,
    color: '#ffedd5',
    marginTop: 4,
    fontWeight: '600',
  },
  heroDotsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 12,
  },
  heroPillActive: {
    width: 20,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#ffffff',
  },
  heroDot: {
    width: 6,
    height: 5,
    borderRadius: 3,
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
  },

  // Section Headers
  sectionTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  sectionTitleWithIcon: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  sectionHeaderTitle: {
    fontSize: 17,
    fontWeight: '900',
    color: COLORS.textMain,
    letterSpacing: -0.3,
  },
  sectionHeaderSubtitle: {
    fontSize: 12,
    color: COLORS.textMuted,
    fontWeight: '500',
  },
  seeAllOrangeLink: {
    fontSize: 13,
    fontWeight: '800',
    color: COLORS.primary,
  },

  // Quick Category Grid (8 Items 4x2)
  categoryGrid4x2: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 24,
    gap: 10,
  },
  categoryCardItem: {
    width: (width - 32 - 30) / 4,
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 4,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  categoryCardItemActive: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.primaryLight,
  },
  categoryIconBadge: {
    width: 46,
    height: 46,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
  },
  categoryCardLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.textBody,
    textAlign: 'center',
  },

  // Product Grid
  featuredProductGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 24,
  },
  featuredCard: {
    width: (width - 32 - 12) / 2,
    backgroundColor: COLORS.surface,
    borderRadius: 18,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
    marginBottom: 4,
  },
  featuredThumbBox: {
    height: 130,
    backgroundColor: '#f8fafc',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    borderBottomWidth: 1,
    borderColor: COLORS.borderLight,
  },
  discountTagBadge: {
    position: 'absolute',
    top: 8,
    left: 8,
    backgroundColor: COLORS.primary,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 8,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 2,
    zIndex: 2,
  },
  discountTagText: {
    color: '#ffffff',
    fontSize: 10.5,
    fontWeight: '900',
  },
  stockPillBadge: {
    position: 'absolute',
    bottom: 6,
    left: 8,
    backgroundColor: 'rgba(15, 23, 42, 0.8)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  stockPillText: {
    color: '#ffffff',
    fontSize: 9.5,
    fontWeight: '700',
  },
  heartBtn: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    zIndex: 2,
  },
  featuredCardBody: {
    padding: 12,
  },
  featuredBrandRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  featuredBrandName: {
    fontSize: 10.5,
    color: COLORS.primary,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  featuredProductName: {
    fontSize: 13,
    fontWeight: '800',
    color: COLORS.textMain,
    marginTop: 4,
    lineHeight: 18,
    height: 36,
  },
  featuredRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 4,
  },
  featuredPriceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 6,
    paddingTop: 6,
    borderTopWidth: 1,
    borderColor: COLORS.borderLight,
  },
  featuredProductPrice: {
    fontSize: 16,
    fontWeight: '900',
    color: COLORS.textMain,
  },
  featuredUnitLabel: {
    fontSize: 10.5,
    color: COLORS.textMuted,
    fontWeight: '500',
  },
  featuredAddBtn: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  featuredAddBtnText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '900',
    marginTop: -2,
  },

  // =========================================================================
  // 2. CATEGORIES & PRODUCT BROWSER SCREEN STYLES
  // =========================================================================
  categoriesHeader: {
    backgroundColor: COLORS.navy,
    paddingTop: Platform.OS === 'ios' ? 20 : 16,
    paddingBottom: 20,
    paddingHorizontal: 18,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    shadowColor: COLORS.navyDark,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 6,
  },
  categoriesHeaderTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#ffffff',
    letterSpacing: -0.4,
  },
  categoriesHeaderSubtitle: {
    fontSize: 13,
    color: '#94a3b8',
    marginTop: 4,
    fontWeight: '500',
  },
  categoryRowCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.surface,
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
    marginBottom: 10,
  },
  categoryRowIconBox: {
    width: 52,
    height: 52,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  categoryRowTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: COLORS.textMain,
  },
  categoryRowCount: {
    fontSize: 12.5,
    color: COLORS.textMuted,
    marginTop: 2,
    fontWeight: '500',
  },
  categoryRowChevron: {
    fontSize: 22,
    color: '#cbd5e1',
    fontWeight: '800',
    paddingRight: 4,
  },

  // Horizontal Category Filter Pills
  filterPillScroll: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    gap: 8,
  },
  filterPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: COLORS.surface,
    borderWidth: 1.5,
    borderColor: COLORS.border,
  },
  filterPillActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 2,
  },
  filterPillText: {
    fontSize: 12.5,
    fontWeight: '700',
    color: COLORS.textBody,
  },
  filterPillTextActive: {
    color: '#ffffff',
    fontWeight: '800',
  },

  // =========================================================================
  // 3. CART & CHECKOUT STYLES
  // =========================================================================
  cartTopHeader: {
    backgroundColor: COLORS.surface,
    paddingVertical: 18,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderColor: COLORS.border,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cartTopTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: COLORS.textMain,
    letterSpacing: -0.3,
  },
  cartItemBadgeCount: {
    backgroundColor: COLORS.primaryLight,
    borderWidth: 1,
    borderColor: COLORS.primaryBorder,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  cartItemBadgeCountText: {
    fontSize: 12,
    fontWeight: '800',
    color: COLORS.primaryDark,
  },
  cartEmptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
    paddingHorizontal: 30,
  },
  cartEmptyIconCircle: {
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: COLORS.surfaceSubtle,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    borderWidth: 2,
    borderColor: COLORS.border,
  },
  cartEmptyTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: COLORS.textMain,
    marginBottom: 6,
  },
  cartEmptySubtitle: {
    fontSize: 13.5,
    color: COLORS.textMuted,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 24,
    maxWidth: 280,
  },
  startShoppingBtn: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 28,
    paddingVertical: 14,
    borderRadius: 14,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 4,
  },
  startShoppingBtnText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '800',
  },
  cartItemCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 1,
  },
  cartItemThumb: {
    width: 54,
    height: 54,
    borderRadius: 14,
    backgroundColor: '#f8fafc',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    marginRight: 12,
  },
  cartQtyControls: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.surfaceSubtle,
    borderRadius: 10,
    padding: 3,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  qtyBtn: {
    width: 28,
    height: 28,
    backgroundColor: COLORS.surface,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
  },
  qtyBtnText: {
    fontWeight: '900',
    fontSize: 15,
    color: COLORS.textMain,
  },
  qtyValueText: {
    marginHorizontal: 10,
    fontWeight: '800',
    fontSize: 13,
    color: COLORS.textMain,
    minWidth: 18,
    textAlign: 'center',
  },
  cartItemDeleteBtn: {
    padding: 6,
    marginLeft: 6,
  },

  // Voucher Box
  voucherBox: {
    flexDirection: 'row',
    marginVertical: 12,
    gap: 8,
  },
  voucherInput: {
    flex: 1,
    backgroundColor: COLORS.surface,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === 'ios' ? 12 : 8,
    fontSize: 13,
    color: COLORS.textMain,
    fontWeight: '600',
  },
  voucherBtn: {
    backgroundColor: COLORS.navy,
    paddingHorizontal: 18,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  voucherBtnText: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 13,
  },

  // Payment Options
  payOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 14,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
    marginBottom: 8,
  },
  payOptionActive: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.primaryLight,
  },
  payOptionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  payOptionLabel: {
    fontWeight: '700',
    fontSize: 13.5,
    color: COLORS.textMain,
  },

  // Summary Card
  summaryCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginVertical: 12,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 1,
  },
  summaryHeader: {
    fontSize: 14,
    fontWeight: '800',
    color: COLORS.textMain,
    marginBottom: 10,
    borderBottomWidth: 1,
    borderColor: COLORS.borderLight,
    paddingBottom: 6,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 4,
  },
  summaryLabel: {
    fontSize: 13,
    color: COLORS.textMuted,
    fontWeight: '500',
  },
  summaryVal: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.textMain,
  },
  summaryTotalRow: {
    borderTopWidth: 1.5,
    borderColor: COLORS.border,
    paddingTop: 10,
    marginTop: 8,
  },

  // =========================================================================
  // 4. ORDERS & TRACKER STYLES
  // =========================================================================
  ordersTopHeader: {
    backgroundColor: COLORS.navy,
    paddingTop: Platform.OS === 'ios' ? 20 : 16,
    paddingBottom: 16,
    paddingHorizontal: 20,
  },
  ordersTopTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#ffffff',
    letterSpacing: -0.3,
  },
  ordersTopSubtitle: {
    fontSize: 13,
    color: '#94a3b8',
    marginTop: 2,
    fontWeight: '500',
  },
  ordersFilterBar: {
    flexDirection: 'row',
    backgroundColor: COLORS.surface,
    borderBottomWidth: 1,
    borderColor: COLORS.border,
  },
  ordersFilterTab: {
    flex: 1,
    paddingVertical: 13,
    alignItems: 'center',
    position: 'relative',
  },
  ordersFilterTabText: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.textMuted,
  },
  ordersFilterTabTextActive: {
    color: COLORS.primary,
    fontWeight: '800',
  },
  ordersActiveIndicator: {
    position: 'absolute',
    bottom: 0,
    left: 10,
    right: 10,
    height: 3,
    backgroundColor: COLORS.primary,
    borderRadius: 2,
  },
  ordersEmptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
    paddingHorizontal: 30,
  },
  ordersEmptyIconCircle: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: COLORS.surfaceSubtle,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    borderWidth: 2,
    borderColor: COLORS.border,
  },
  ordersEmptyTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: COLORS.textMain,
    marginBottom: 4,
  },
  ordersEmptySubtitle: {
    fontSize: 13,
    color: COLORS.textMuted,
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 18,
  },
  orderCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  orderHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderColor: COLORS.borderLight,
  },
  orderNumberTag: {
    fontSize: 13.5,
    fontWeight: '800',
    color: COLORS.textMain,
  },
  orderStatusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    fontWeight: '800',
    fontSize: 11.5,
  },
  orderFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderColor: COLORS.borderLight,
    paddingTop: 10,
    marginTop: 10,
  },
  trackBtn: {
    backgroundColor: COLORS.navy,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  trackBtnText: {
    color: '#ffffff',
    fontSize: 11.5,
    fontWeight: '800',
  },

  // =========================================================================
  // 5. PROFILE SCREEN STYLES
  // =========================================================================
  profileTopHeader: {
    backgroundColor: COLORS.navy,
    paddingTop: Platform.OS === 'ios' ? 24 : 20,
    paddingBottom: 24,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    shadowColor: COLORS.navyDark,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 14,
    elevation: 8,
  },
  profileUserRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  profileAvatarBox: {
    width: 64,
    height: 64,
    borderRadius: 20,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 5,
  },
  profileAvatarText: {
    fontSize: 28,
    fontWeight: '900',
    color: '#ffffff',
  },
  profileUserName: {
    fontSize: 19,
    fontWeight: '900',
    color: '#ffffff',
    letterSpacing: -0.3,
  },
  profileUserEmail: {
    fontSize: 13,
    color: '#94a3b8',
    marginTop: 2,
    fontWeight: '500',
  },
  profileContractorBadge: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(249, 115, 22, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(249, 115, 22, 0.4)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
    marginTop: 4,
  },
  profileContractorBadgeText: {
    color: '#fed7aa',
    fontSize: 10.5,
    fontWeight: '800',
  },
  profileGearBtn: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: COLORS.navyCard,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.navyMuted,
  },
  profileStatsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  profileStatCard: {
    flex: 1,
    backgroundColor: COLORS.navyCard,
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.navyMuted,
  },
  profileStatValue: {
    fontSize: 19,
    fontWeight: '900',
    color: '#ffffff',
  },
  profileStatLabel: {
    fontSize: 11,
    color: '#94a3b8',
    marginTop: 2,
    fontWeight: '600',
  },
  profileSectionEyebrow: {
    fontSize: 11.5,
    fontWeight: '800',
    color: COLORS.textMuted,
    letterSpacing: 0.6,
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  profileGroupCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.border,
    overflow: 'hidden',
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 1,
  },
  profileRowItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderColor: COLORS.borderLight,
  },
  profileRowLabel: {
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.textMain,
  },
  profileNotifBadge: {
    backgroundColor: COLORS.primary,
    borderRadius: 10,
    paddingHorizontal: 7,
    paddingVertical: 2,
    marginRight: 6,
  },
  profileNotifBadgeText: {
    color: '#ffffff',
    fontSize: 10.5,
    fontWeight: '800',
  },
  profileRowChevron: {
    fontSize: 20,
    color: '#cbd5e1',
    fontWeight: '800',
  },
  profileSignOutBtn: {
    marginTop: 20,
    backgroundColor: COLORS.dangerBg,
    borderWidth: 1.5,
    borderColor: COLORS.dangerBorder,
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 30,
  },
  profileSignOutText: {
    color: '#dc2626',
    fontSize: 14.5,
    fontWeight: '800',
  },

  // =========================================================================
  // 6. BOTTOM NAVIGATION BAR
  // =========================================================================
  bottomNav: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: Platform.OS === 'ios' ? 76 : 64,
    paddingBottom: Platform.OS === 'ios' ? 14 : 0,
    backgroundColor: COLORS.surface,
    borderTopWidth: 1,
    borderColor: COLORS.border,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 10,
  },
  navItem: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  navPillActive: {
    backgroundColor: COLORS.primaryLight,
    borderRadius: 16,
  },
  navText: {
    fontSize: 10.5,
    fontWeight: '700',
    color: COLORS.textMuted,
    marginTop: 2,
  },
  navTextActive: {
    color: COLORS.primary,
    fontWeight: '900',
  },
  navBadge: {
    position: 'absolute',
    top: 0,
    right: 6,
    backgroundColor: COLORS.primary,
    borderRadius: 10,
    minWidth: 18,
    height: 18,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: COLORS.surface,
  },
  navBadgeText: {
    color: '#ffffff',
    fontSize: 9.5,
    fontWeight: '900',
  },

  // =========================================================================
  // 7. MODALS & SHEET STYLES
  // =========================================================================
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.7)',
    justifyContent: 'flex-end',
  },
  modalSheetContainer: {
    backgroundColor: COLORS.surface,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingTop: 12,
    paddingHorizontal: 20,
    paddingBottom: Platform.OS === 'ios' ? 34 : 20,
    maxHeight: '88%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -10 },
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 20,
  },
  sheetDragHandle: {
    width: 40,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: '#cbd5e1',
    alignSelf: 'center',
    marginBottom: 14,
  },
  modalNav: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderColor: COLORS.borderLight,
    marginBottom: 12,
  },
  modalNavTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: COLORS.textMain,
    letterSpacing: -0.3,
  },
  modalCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.surfaceSubtle,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalCloseBtnText: {
    fontSize: 16,
    color: COLORS.textMuted,
    fontWeight: '700',
  },
  detailThumb: {
    height: 170,
    backgroundColor: '#f8fafc',
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 10,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
  },
  driverCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.navyCard,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.navyMuted,
  },

  // =========================================================================
  // 8. LOGOUT CONFIRMATION MODAL
  // =========================================================================
  confirmModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.75)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  confirmModalCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: COLORS.surface,
    borderRadius: 24,
    padding: 24,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.25,
    shadowRadius: 24,
    elevation: 10,
  },
  confirmModalIconCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: COLORS.dangerBg,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    borderWidth: 2,
    borderColor: COLORS.dangerBorder,
  },
  confirmModalTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: COLORS.textMain,
    marginBottom: 8,
  },
  confirmModalMessage: {
    fontSize: 13.5,
    color: COLORS.textMuted,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 24,
  },
  confirmModalActions: {
    flexDirection: 'row',
    gap: 10,
    width: '100%',
  },
  confirmCancelBtn: {
    flex: 1,
    height: 48,
    borderRadius: 14,
    backgroundColor: COLORS.surfaceSubtle,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  confirmCancelBtnText: {
    fontSize: 14,
    fontWeight: '800',
    color: COLORS.textBody,
  },
  confirmLogoutBtn: {
    flex: 1,
    height: 48,
    borderRadius: 14,
    backgroundColor: COLORS.danger,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: COLORS.danger,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 3,
  },
  confirmLogoutBtnText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#ffffff',
  },

  // =========================================================================
  // 9. SPLASH SCREEN STYLES
  // =========================================================================
  splashContainer: {
    flex: 1,
    backgroundColor: COLORS.navyDark,
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 50,
    paddingHorizontal: 24,
  },
  splashOrbTop: {
    position: 'absolute',
    top: -80,
    right: -80,
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: 'rgba(249, 115, 22, 0.08)',
  },
  splashOrbBottom: {
    position: 'absolute',
    bottom: -100,
    left: -100,
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: 'rgba(234, 88, 12, 0.12)',
  },
  splashCenter: {
    alignItems: 'center',
    marginTop: height * 0.25,
  },
  splashLogoBox: {
    width: 80,
    height: 80,
    borderRadius: 24,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 10,
    marginBottom: 20,
  },
  splashLogoText: {
    fontSize: 26,
    fontWeight: '900',
    color: '#ffffff',
    letterSpacing: 0.5,
  },
  splashTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: '#ffffff',
    letterSpacing: -0.5,
  },
  splashSubtitle: {
    fontSize: 15,
    fontWeight: '800',
    color: COLORS.primary,
    marginTop: 4,
    letterSpacing: 0.2,
  },
  splashTagline: {
    fontSize: 13.5,
    color: '#94a3b8',
    textAlign: 'center',
    marginTop: 20,
    lineHeight: 20,
    maxWidth: 280,
    fontWeight: '500',
  },
  splashFooter: {
    alignItems: 'center',
    marginBottom: 20,
  },
  splashLoadingText: {
    fontSize: 12,
    color: '#94a3b8',
    marginTop: 10,
    fontWeight: '600',
  },

  // =========================================================================
  // 10. ONBOARDING STYLES
  // =========================================================================
  onboardingContainer: {
    flex: 1,
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingVertical: 20,
  },
  onboardingHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
  },
  skipBtn: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    paddingHorizontal: 16,
    paddingVertical: 7,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  skipBtnText: {
    fontSize: 13,
    fontWeight: '800',
    color: COLORS.textBody,
  },
  onboardingBody: {
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  onboardingIconCircle: {
    width: 170,
    height: 170,
    borderRadius: 85,
    backgroundColor: COLORS.surface,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 6,
    marginBottom: 36,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
  },
  onboardingTitle: {
    fontSize: 24,
    fontWeight: '900',
    color: COLORS.textMain,
    textAlign: 'center',
    marginBottom: 12,
    letterSpacing: -0.4,
  },
  onboardingDesc: {
    fontSize: 14,
    color: COLORS.textBody,
    textAlign: 'center',
    lineHeight: 22,
    maxWidth: 300,
    fontWeight: '500',
  },
  onboardingFooter: {
    marginBottom: 24,
  },
  dotsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    marginBottom: 24,
  },
  dot: {
    height: 8,
    borderRadius: 4,
  },
  activeDot: {
    width: 24,
  },
  inactiveDot: {
    width: 8,
    backgroundColor: '#cbd5e1',
  },

  // Button primitives
  primaryAuthBtn: {
    backgroundColor: COLORS.primary,
    height: 52,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 4,
  },
  primaryAuthBtnText: {
    color: '#ffffff',
    fontSize: 15.5,
    fontWeight: '900',
    letterSpacing: -0.2,
  },
  secondaryAuthBtn: {
    backgroundColor: COLORS.surface,
    height: 52,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  secondaryAuthBtnText: {
    color: COLORS.primary,
    fontSize: 15,
    fontWeight: '800',
  },

  // =========================================================================
  // 11. AUTH / SIGN IN & SIGN UP STYLES
  // =========================================================================
  authContainer: {
    flex: 1,
    backgroundColor: COLORS.surface,
  },
  authTopHeader: {
    backgroundColor: COLORS.navy,
    paddingTop: Platform.OS === 'ios' ? 36 : 28,
    paddingBottom: 28,
    paddingHorizontal: 24,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
  },
  authMiniBrand: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 20,
  },
  authMiniLogoBox: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 3,
  },
  authMiniLogoText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '900',
  },
  authMiniTitle: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '900',
  },
  authMiniSubtitle: {
    color: COLORS.primary,
    fontSize: 10.5,
    fontWeight: '700',
  },
  authHeroTitle: {
    fontSize: 26,
    fontWeight: '900',
    color: '#ffffff',
    letterSpacing: -0.5,
  },
  authHeroSubtitle: {
    fontSize: 13.5,
    color: '#94a3b8',
    marginTop: 4,
    fontWeight: '500',
  },
  authFormCard: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 24,
  },
  authFieldGroup: {
    marginBottom: 16,
  },
  authFieldLabel: {
    fontSize: 13.5,
    fontWeight: '800',
    color: COLORS.textMain,
    marginBottom: 8,
  },
  authInput: {
    backgroundColor: COLORS.surface,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === 'ios' ? 14 : 10,
    fontSize: 14,
    color: COLORS.textMain,
    fontWeight: '600',
  },
  authPasswordInputBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.surface,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    borderRadius: 14,
    paddingRight: 12,
  },
  eyeBtn: {
    padding: 8,
  },
  authOptionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 4,
    marginBottom: 24,
  },
  rememberMeBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 7,
    borderWidth: 1.5,
    borderColor: '#cbd5e1',
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  checkmark: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '900',
  },
  rememberMeText: {
    fontSize: 13,
    color: COLORS.textBody,
    fontWeight: '600',
  },
  forgotPasswordText: {
    fontSize: 13,
    color: COLORS.primaryDark,
    fontWeight: '800',
  },
  authFooterRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 30,
  },
  authFooterText: {
    fontSize: 13.5,
    color: COLORS.textMuted,
    fontWeight: '500',
  },
  authFooterLink: {
    fontSize: 13.5,
    color: COLORS.primary,
    fontWeight: '800',
  },
  
  // Toast
  toast: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 52 : 36,
    alignSelf: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.95)',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 24,
    zIndex: 99999,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  toastText: {
    color: '#ffffff',
    fontSize: 13.5,
    fontWeight: '800',
  },
});
