<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use App\Models\ProductVariant;
use App\Models\InventoryBatch;
use App\Models\Supplier;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class JemInventorySeeder extends Seeder
{
    public function run(): void
    {
        // 1. Ensure Foreign Key constraints are disabled during clean wipe
        Schema::disableForeignKeyConstraints();

        // Clear dependent order/cart/inventory tables that reference old products
        if (Schema::hasTable('cart_items')) {
            DB::table('cart_items')->truncate();
        }
        if (Schema::hasTable('order_adjustments')) {
            DB::table('order_adjustments')->truncate();
        }
        if (Schema::hasTable('backorders')) {
            DB::table('backorders')->truncate();
        }
        if (Schema::hasTable('order_items')) {
            DB::table('order_items')->truncate();
        }
        if (Schema::hasTable('orders')) {
            DB::table('orders')->truncate();
        }
        if (Schema::hasTable('stock_adjustments')) {
            DB::table('stock_adjustments')->truncate();
        }
        if (Schema::hasTable('restock_requests')) {
            DB::table('restock_requests')->truncate();
        }
        if (Schema::hasTable('inventory_batches')) {
            DB::table('inventory_batches')->truncate();
        }
        if (Schema::hasTable('product_variants')) {
            DB::table('product_variants')->truncate();
        }
        if (Schema::hasTable('customer_wishlists')) {
            DB::table('customer_wishlists')->truncate();
        }
        if (Schema::hasTable('products')) {
            DB::table('products')->truncate();
        }

        Schema::enableForeignKeyConstraints();

        // 2. Ensure Categories Exist
        $categoryData = [
            'Lumber' => 'Marine Plywood, Ordinary Plywood, Smart Board, Hardiflex, and Phenolic Boards',
            'Roofing & Steel' => 'Welded screens, aluminum screens, mosquito screen, green screens, and nets',
            'Pipes' => 'Polyethylene (PE) pipes and irrigation pipes',
            'Plumbing' => 'PE compression fittings, PVC blue potable fittings, PVC sanitary fittings, and GI nipples',
            'Fasteners & Screws' => 'Stainless hose clamps, cup hooks, and fixing hardware',
            'Hardware & Accessories' => 'Heavy-duty poly ropes, hardware cloth, and utility accessories',
            'Paint & Finishes' => 'PVC tile trims, trims, sealants, and finishes',
            'Tarpaulin & Covers' => 'Trapal baga heavy-duty and trapal nipis light-duty tarpaulins',
        ];

        $categories = [];
        foreach ($categoryData as $name => $desc) {
            $categories[$name] = Category::firstOrCreate(
                ['name' => $name],
                ['description' => $desc, 'status' => 'active']
            );
        }

        // 3. Ensure Brands Exist
        $brandData = [
            'JEM Lumber' => 'JEM Hardware house brand lumber and wood boards',
            'Neltex' => 'Neltex high-grade PVC pipes and precision fittings',
            'Hardiflex' => 'Hardiflex fiber cement building boards',
            'SmartBoard' => 'SCG SmartBoard fiber cement ceiling and wall boards',
            'Generic' => 'Standard industrial hardware and plumbing commodities',
        ];

        $brands = [];
        foreach ($brandData as $name => $desc) {
            $brands[$name] = Brand::firstOrCreate(
                ['name' => $name],
                ['description' => $desc, 'status' => 'active']
            );
        }

        // 4. Ensure Supplier Exists
        $supplier = null;
        if (Schema::hasTable('suppliers')) {
            $supplier = Supplier::firstOrCreate(
                ['name' => 'Metro Hardware Distributors'],
                [
                    'contact_person' => 'Juan Reyes',
                    'email' => 'sales@metrohardware.ph',
                    'phone' => '+639170001122',
                    'address' => 'Binondo, Manila',
                    'status' => 'active'
                ]
            );
        }

        // 5. Physical Inventory Items Transcribed From JEM Hardware Price Lists
        $items = [
            // ==========================================
            // SHEET 1: MARINE PLYWOOD, ORDINARY PLYWOOD, HARDELITE / BOARDS
            // ==========================================
            [
                'name' => 'Marine Plywood 3/4"',
                'sku' => 'JEM-MPLY-34',
                'category' => 'Lumber',
                'brand' => 'JEM Lumber',
                'unit' => 'sheet',
                'size' => '3/4"',
                'selling_price' => 1080.00,
                'cost_price' => 830.00,
                'stock' => 50,
                'description' => '3/4" Waterproof marine-grade plywood suitable for boat building, exterior ceilings, concrete formworks, and wet-area cabinetry.',
            ],
            [
                'name' => 'Marine Plywood 1/2"',
                'sku' => 'JEM-MPLY-12',
                'category' => 'Lumber',
                'brand' => 'JEM Lumber',
                'unit' => 'sheet',
                'size' => '1/2"',
                'selling_price' => 690.00,
                'cost_price' => 535.00,
                'stock' => 60,
                'description' => '1/2" Marine plywood with water-resistant glue lines, ideal for bathroom partitions, eaves, and outdoor cabinetry.',
            ],
            [
                'name' => 'Marine Plywood 1/4"',
                'sku' => 'JEM-MPLY-14',
                'category' => 'Lumber',
                'brand' => 'JEM Lumber',
                'unit' => 'sheet',
                'size' => '1/4"',
                'selling_price' => 395.00,
                'cost_price' => 235.00,
                'stock' => 75,
                'description' => '1/4" Marine plywood board for ceiling panels, interior lining, and moisture-prone backing panels.',
            ],
            [
                'name' => 'Marine Plywood 3/16"',
                'sku' => 'JEM-MPLY-316',
                'category' => 'Lumber',
                'brand' => 'JEM Lumber',
                'unit' => 'sheet',
                'size' => '3/16"',
                'selling_price' => 275.00,
                'cost_price' => 155.00,
                'stock' => 80,
                'description' => '3/16" Marine plywood lightweight panel for curved surfaces, ceilings, and delicate woodworking projects.',
            ],
            [
                'name' => 'Ordinary Plywood 3/4"',
                'sku' => 'JEM-OPLY-34',
                'category' => 'Lumber',
                'brand' => 'JEM Lumber',
                'unit' => 'sheet',
                'size' => '3/4"',
                'selling_price' => 990.00,
                'cost_price' => 770.00,
                'stock' => 50,
                'description' => '3/4" Standard ordinary plywood for heavy furniture, sub-flooring, shelving, and interior partitions.',
            ],
            [
                'name' => 'Ordinary Plywood 1/2"',
                'sku' => 'JEM-OPLY-12',
                'category' => 'Lumber',
                'brand' => 'JEM Lumber',
                'unit' => 'sheet',
                'size' => '1/2"',
                'selling_price' => 590.00,
                'cost_price' => 470.00,
                'stock' => 60,
                'description' => '1/2" Ordinary plywood for furniture backings, room dividers, and general carpentry works.',
            ],
            [
                'name' => 'Ordinary Plywood 1/4"',
                'sku' => 'JEM-OPLY-14',
                'category' => 'Lumber',
                'brand' => 'JEM Lumber',
                'unit' => 'sheet',
                'size' => '1/4"',
                'selling_price' => 295.00,
                'cost_price' => 230.00,
                'stock' => 85,
                'description' => '1/4" Standard ordinary plywood for drywall partitions, ceilings, door skins, and crafts.',
            ],
            [
                'name' => 'Hardiflex Board 3.5mm',
                'sku' => 'JEM-HARDI-35',
                'category' => 'Lumber',
                'brand' => 'Hardiflex',
                'unit' => 'sheet',
                'size' => '3.5mm',
                'selling_price' => 280.00,
                'cost_price' => 230.00,
                'stock' => 65,
                'description' => '3.5mm Hardiflex fiber cement board for fire-resistant, termite-proof, and moisture-resistant interior ceilings.',
            ],
            [
                'name' => 'Hardiflex Board 4.5mm',
                'sku' => 'JEM-HARDI-45',
                'category' => 'Lumber',
                'brand' => 'Hardiflex',
                'unit' => 'sheet',
                'size' => '4.5mm',
                'selling_price' => 370.00,
                'cost_price' => 300.00,
                'stock' => 60,
                'description' => '4.5mm Hardiflex durable fiber cement board for internal wall linings, eaves, and heavy-duty ceilings.',
            ],
            [
                'name' => 'Smart Board 3.5mm',
                'sku' => 'JEM-SMART-35',
                'category' => 'Lumber',
                'brand' => 'SmartBoard',
                'unit' => 'sheet',
                'size' => '3.5mm',
                'selling_price' => 290.00,
                'cost_price' => 240.00,
                'stock' => 55,
                'description' => '3.5mm SCG SmartBoard high-strength fiber cement ceiling sheet with exceptional water and termite resistance.',
            ],
            [
                'name' => 'Smart Board 4.5mm',
                'sku' => 'JEM-SMART-45',
                'category' => 'Lumber',
                'brand' => 'SmartBoard',
                'unit' => 'sheet',
                'size' => '4.5mm',
                'selling_price' => 365.00,
                'cost_price' => 290.00,
                'stock' => 50,
                'description' => '4.5mm SCG SmartBoard robust fiber cement board for wall partitions and acoustic dampening.',
            ],
            [
                'name' => 'Phenolic Board 1/2"',
                'sku' => 'JEM-PHEN-12',
                'category' => 'Lumber',
                'brand' => 'JEM Lumber',
                'unit' => 'sheet',
                'size' => '1/2"',
                'selling_price' => 1095.00,
                'cost_price' => 830.00,
                'stock' => 45,
                'description' => '1/2" Film-faced phenolic plywood board for reusable, mirror-finish concrete formwork construction.',
            ],
            [
                'name' => 'Phenolic Board 3/4"',
                'sku' => 'JEM-PHEN-34',
                'category' => 'Lumber',
                'brand' => 'JEM Lumber',
                'unit' => 'sheet',
                'size' => '3/4"',
                'selling_price' => 1395.00,
                'cost_price' => 1200.00,
                'stock' => 40,
                'description' => '3/4" Heavy-duty black film phenolic board engineered for multi-pour high-rise concrete casting.',
            ],

            // ==========================================
            // SHEET 2: WELDED SCREEN, SCREENS, GREEN SCREEN 3FT & 4FT
            // ==========================================
            [
                'name' => 'Welded Screen 1/2" × 4ft × 25M',
                'sku' => 'JEM-WELD-12425',
                'category' => 'Roofing & Steel',
                'brand' => 'Generic',
                'unit' => 'meter',
                'size' => '1/2" x 4ft x 25M',
                'selling_price' => 140.00,
                'cost_price' => 105.00,
                'stock' => 120,
                'description' => '1/2" mesh galvanized welded wire screen (4ft width) sold per meter or wholesale roll (25 meters). Great for cages and fencing.',
            ],
            [
                'name' => 'Welded Screen 1" × 4ft × 25M',
                'sku' => 'JEM-WELD-10425',
                'category' => 'Roofing & Steel',
                'brand' => 'Generic',
                'unit' => 'meter',
                'size' => '1" x 4ft x 25M',
                'selling_price' => 140.00,
                'cost_price' => 95.00,
                'stock' => 100,
                'description' => '1" mesh galvanized welded wire screen (4ft width) sold per meter or wholesale roll. Rust-resistant protective wire.',
            ],
            [
                'name' => 'Aluminum Screen 3ft',
                'sku' => 'JEM-ALUM-3FT',
                'category' => 'Roofing & Steel',
                'brand' => 'Generic',
                'unit' => 'meter',
                'size' => '3ft',
                'selling_price' => 180.00,
                'cost_price' => 135.00,
                'stock' => 80,
                'description' => '3-foot width rust-proof aluminum insect screen wire mesh for residential windows and screen doors.',
            ],
            [
                'name' => 'Aluminum Screen 4ft',
                'sku' => 'JEM-ALUM-4FT',
                'category' => 'Roofing & Steel',
                'brand' => 'Generic',
                'unit' => 'meter',
                'size' => '4ft',
                'selling_price' => 220.00,
                'cost_price' => 165.00,
                'stock' => 80,
                'description' => '4-foot width rust-proof aluminum insect screen wire mesh for wide windows and patio doors.',
            ],
            [
                'name' => 'Mosquito Screen 3ft',
                'sku' => 'JEM-MOSQ-3FT',
                'category' => 'Roofing & Steel',
                'brand' => 'Generic',
                'unit' => 'meter',
                'size' => '3ft',
                'selling_price' => 75.00,
                'cost_price' => 45.00,
                'stock' => 150,
                'description' => '3-foot nylon mosquito mesh for affordable, durable insect and pest protection on windows.',
            ],
            [
                'name' => 'Ayagan / Hardware Cloth 3ft',
                'sku' => 'JEM-AYAG-3FT',
                'category' => 'Hardware & Accessories',
                'brand' => 'Generic',
                'unit' => 'meter',
                'size' => '3ft',
                'selling_price' => 95.00,
                'cost_price' => 60.00,
                'stock' => 100,
                'description' => '3-foot wire cloth sifter mesh (ayagan) for gravel, sand sieving, and chicken wire enclosures.',
            ],
            [
                'name' => 'Green Screen 1/8" (3ft × 30M)',
                'sku' => 'JEM-GSCR-3-18',
                'category' => 'Roofing & Steel',
                'brand' => 'Generic',
                'unit' => 'meter',
                'size' => '1/8" x 3ft',
                'selling_price' => 110.00,
                'cost_price' => 70.00,
                'stock' => 90,
                'description' => '3-foot wide 1/8" fine mesh green plastic screen for poultry, garden protection, and fencing.',
            ],
            [
                'name' => 'Green Screen 1/4" (3ft × 30M)',
                'sku' => 'JEM-GSCR-3-14',
                'category' => 'Roofing & Steel',
                'brand' => 'Generic',
                'unit' => 'meter',
                'size' => '1/4" x 3ft',
                'selling_price' => 120.00,
                'cost_price' => 75.00,
                'stock' => 90,
                'description' => '3-foot wide 1/4" mesh green plastic garden and poultry screen net.',
            ],
            [
                'name' => 'Green Screen 1/2" (3ft × 30M)',
                'sku' => 'JEM-GSCR-3-12',
                'category' => 'Roofing & Steel',
                'brand' => 'Generic',
                'unit' => 'meter',
                'size' => '1/2" x 3ft',
                'selling_price' => 155.00,
                'cost_price' => 110.00,
                'stock' => 90,
                'description' => '3-foot wide 1/2" medium mesh green plastic net for agricultural and construction perimeter netting.',
            ],
            [
                'name' => 'Green Screen 3/4" (3ft × 30M)',
                'sku' => 'JEM-GSCR-3-34',
                'category' => 'Roofing & Steel',
                'brand' => 'Generic',
                'unit' => 'meter',
                'size' => '3/4" x 3ft',
                'selling_price' => 150.00,
                'cost_price' => 105.00,
                'stock' => 90,
                'description' => '3-foot wide 3/4" mesh heavy-duty green screen roll sold per meter.',
            ],
            [
                'name' => 'Green Screen 1/8" (4ft × 30M)',
                'sku' => 'JEM-GSCR-4-18',
                'category' => 'Roofing & Steel',
                'brand' => 'Generic',
                'unit' => 'meter',
                'size' => '1/8" x 4ft',
                'selling_price' => 185.00,
                'cost_price' => 120.00,
                'stock' => 90,
                'description' => '4-foot wide 1/8" high-density green screen for dust barrier and wind protection.',
            ],
            [
                'name' => 'Green Screen 1/2" (4ft × 30M)',
                'sku' => 'JEM-GSCR-4-12',
                'category' => 'Roofing & Steel',
                'brand' => 'Generic',
                'unit' => 'meter',
                'size' => '1/2" x 4ft',
                'selling_price' => 195.00,
                'cost_price' => 145.00,
                'stock' => 90,
                'description' => '4-foot wide 1/2" green plastic mesh screen for construction safety and animal enclosures.',
            ],
            [
                'name' => 'Green Screen 1" (4ft × 30M)',
                'sku' => 'JEM-GSCR-4-10',
                'category' => 'Roofing & Steel',
                'brand' => 'Generic',
                'unit' => 'meter',
                'size' => '1" x 4ft',
                'selling_price' => 205.00,
                'cost_price' => 150.00,
                'stock' => 90,
                'description' => '4-foot wide 1" wide mesh heavy-duty green screen mesh.',
            ],
            [
                'name' => 'Green Screen 90M Single 4ft Net',
                'sku' => 'JEM-GNET-SGL-4',
                'category' => 'Roofing & Steel',
                'brand' => 'Generic',
                'unit' => 'meter',
                'size' => '4ft Single',
                'selling_price' => 60.00,
                'cost_price' => 40.00,
                'stock' => 150,
                'description' => '4-foot single ply agricultural shade net / safety net for construction perimeter and sun shading.',
            ],
            [
                'name' => 'Green Screen Black 90M Single 4ft Net',
                'sku' => 'JEM-BNET-SGL-4',
                'category' => 'Roofing & Steel',
                'brand' => 'Generic',
                'unit' => 'meter',
                'size' => '4ft Single Black',
                'selling_price' => 60.00,
                'cost_price' => 40.00,
                'stock' => 150,
                'description' => '4-foot single ply black shade netting for nursery plants, shading, and site privacy.',
            ],
            [
                'name' => 'Green Screen 90M Double 4ft Net',
                'sku' => 'JEM-GNET-DBL-4',
                'category' => 'Roofing & Steel',
                'brand' => 'Generic',
                'unit' => 'meter',
                'size' => '4ft Double',
                'selling_price' => 75.00,
                'cost_price' => 50.00,
                'stock' => 150,
                'description' => '4-foot double-woven heavy shading green net (70-80% shade factor) for heavy sun protection.',
            ],

            // ==========================================
            // SHEET 3: P.E. FITTINGS, PVC BLUE FITTINGS, G.I. NIPPLE S-20
            // ==========================================
            [
                'name' => 'PE Pipe 1/2"',
                'sku' => 'JEM-PE-PIPE-12',
                'category' => 'Pipes',
                'brand' => 'Generic',
                'unit' => 'meter',
                'size' => '1/2"',
                'selling_price' => 45.00,
                'cost_price' => 32.00,
                'stock' => 200,
                'description' => '1/2" High-density polyethylene flexible pipe for outdoor potable water lines and irrigation.',
            ],
            [
                'name' => 'PE Pipe 3/4"',
                'sku' => 'JEM-PE-PIPE-34',
                'category' => 'Pipes',
                'brand' => 'Generic',
                'unit' => 'meter',
                'size' => '3/4"',
                'selling_price' => 65.00,
                'cost_price' => 48.00,
                'stock' => 200,
                'description' => '3/4" Heavy-duty PE pipe for main water distribution lines and deep well water delivery.',
            ],
            [
                'name' => 'PE Elbow 1/2"',
                'sku' => 'JEM-PE-ELB-12',
                'category' => 'Plumbing',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '1/2"',
                'selling_price' => 35.00,
                'cost_price' => 24.00,
                'stock' => 100,
                'description' => '1/2" PE compression 90-degree elbow for watertight polyethylene pipe turns.',
            ],
            [
                'name' => 'PE Male Elbow 1/2"',
                'sku' => 'JEM-PE-MELB-12',
                'category' => 'Plumbing',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '1/2"',
                'selling_price' => 40.00,
                'cost_price' => 28.00,
                'stock' => 100,
                'description' => '1/2" PE male threaded compression elbow for connecting PE pipes to threaded brass/PVC valves.',
            ],
            [
                'name' => 'PE Female Elbow 1/2"',
                'sku' => 'JEM-PE-FELB-12',
                'category' => 'Plumbing',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '1/2"',
                'selling_price' => 40.00,
                'cost_price' => 28.00,
                'stock' => 100,
                'description' => '1/2" PE female threaded compression elbow for faucets and fixtures.',
            ],
            [
                'name' => 'PE Coupling 1/2"',
                'sku' => 'JEM-PE-COUP-12',
                'category' => 'Plumbing',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '1/2"',
                'selling_price' => 30.00,
                'cost_price' => 20.00,
                'stock' => 120,
                'description' => '1/2" PE straight compression coupling for joining two lengths of 1/2" PE pipe without solvent.',
            ],
            [
                'name' => 'PE Coupling Reducer 1/2" × 3/4"',
                'sku' => 'JEM-PE-CREDUC-1234',
                'category' => 'Plumbing',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '1/2" x 3/4"',
                'selling_price' => 45.00,
                'cost_price' => 30.00,
                'stock' => 100,
                'description' => '1/2" to 3/4" PE compression coupling reducer for transitioning pipe diameters.',
            ],
            [
                'name' => 'PE Tee 1/2"',
                'sku' => 'JEM-PE-TEE-12',
                'category' => 'Plumbing',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '1/2"',
                'selling_price' => 50.00,
                'cost_price' => 35.00,
                'stock' => 100,
                'description' => '1/2" Equal compression tee for branching 1/2" PE water pipelines.',
            ],
            [
                'name' => 'PE Tee Reducer 1/2" × 3/4"',
                'sku' => 'JEM-PE-TREDUC-1234',
                'category' => 'Plumbing',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '1/2" x 3/4"',
                'selling_price' => 60.00,
                'cost_price' => 42.00,
                'stock' => 100,
                'description' => '1/2" × 3/4" PE compression reducing tee for mainline branching.',
            ],
            [
                'name' => 'PE Female Tee 1/2"',
                'sku' => 'JEM-PE-FTEE-12',
                'category' => 'Plumbing',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '1/2"',
                'selling_price' => 55.00,
                'cost_price' => 38.00,
                'stock' => 80,
                'description' => '1/2" PE tee with threaded female branch for installing valves and bibbs.',
            ],
            [
                'name' => 'PE Male Tee 1/2"',
                'sku' => 'JEM-PE-MTEE-12',
                'category' => 'Plumbing',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '1/2"',
                'selling_price' => 55.00,
                'cost_price' => 38.00,
                'stock' => 80,
                'description' => '1/2" PE tee with threaded male center branch for connecting manifold fittings.',
            ],
            [
                'name' => 'PE Male Adaptor 1/2"',
                'sku' => 'JEM-PE-MADAP-12',
                'category' => 'Plumbing',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '1/2"',
                'selling_price' => 30.00,
                'cost_price' => 20.00,
                'stock' => 120,
                'description' => '1/2" PE straight compression to male thread adaptor for water meters and pumps.',
            ],
            [
                'name' => 'PE Female Adaptor 1/2"',
                'sku' => 'JEM-PE-FADAP-12',
                'category' => 'Plumbing',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '1/2"',
                'selling_price' => 30.00,
                'cost_price' => 20.00,
                'stock' => 120,
                'description' => '1/2" PE compression to female thread adaptor for brass nipples and faucets.',
            ],

            // PVC Blue Potable Fittings
            [
                'name' => 'Blue Elbow Plain 1/2"',
                'sku' => 'JEM-BELB-PLN-12',
                'category' => 'Plumbing',
                'brand' => 'Neltex',
                'unit' => 'piece',
                'size' => '1/2"',
                'selling_price' => 15.00,
                'cost_price' => 10.00,
                'stock' => 150,
                'description' => '1/2" PVC blue plain 90-degree socket elbow for potable pressure water piping.',
            ],
            [
                'name' => 'Blue Elbow Threaded 1/2"',
                'sku' => 'JEM-BELB-THRD-12',
                'category' => 'Plumbing',
                'brand' => 'Neltex',
                'unit' => 'piece',
                'size' => '1/2"',
                'selling_price' => 20.00,
                'cost_price' => 14.00,
                'stock' => 120,
                'description' => '1/2" PVC blue 90-degree threaded elbow for standard bibcock and shower connections.',
            ],
            [
                'name' => 'Blue Tee Plain 1/2"',
                'sku' => 'JEM-BTEE-PLN-12',
                'category' => 'Plumbing',
                'brand' => 'Neltex',
                'unit' => 'piece',
                'size' => '1/2"',
                'selling_price' => 20.00,
                'cost_price' => 14.00,
                'stock' => 120,
                'description' => '1/2" PVC blue slip-fit equal tee for clean water distribution lines.',
            ],
            [
                'name' => 'Blue Tee Threaded 1/2"',
                'sku' => 'JEM-BTEE-THRD-12',
                'category' => 'Plumbing',
                'brand' => 'Neltex',
                'unit' => 'piece',
                'size' => '1/2"',
                'selling_price' => 25.00,
                'cost_price' => 17.00,
                'stock' => 100,
                'description' => '1/2" PVC blue tee with threaded central branch for branch fixtures.',
            ],
            [
                'name' => 'Blue Female Adaptor 1/2"',
                'sku' => 'JEM-BFADAP-12',
                'category' => 'Plumbing',
                'brand' => 'Neltex',
                'unit' => 'piece',
                'size' => '1/2"',
                'selling_price' => 18.00,
                'cost_price' => 12.00,
                'stock' => 120,
                'description' => '1/2" PVC blue female threaded adapter socket for valve and bib connections.',
            ],
            [
                'name' => 'Blue Male Adaptor 1/2"',
                'sku' => 'JEM-BMADAP-12',
                'category' => 'Plumbing',
                'brand' => 'Neltex',
                'unit' => 'piece',
                'size' => '1/2"',
                'selling_price' => 18.00,
                'cost_price' => 12.00,
                'stock' => 120,
                'description' => '1/2" PVC blue male threaded adapter socket for pumps and gate valves.',
            ],
            [
                'name' => 'Blue Coupling 1/2"',
                'sku' => 'JEM-BCOUP-12',
                'category' => 'Plumbing',
                'brand' => 'Neltex',
                'unit' => 'piece',
                'size' => '1/2"',
                'selling_price' => 15.00,
                'cost_price' => 10.00,
                'stock' => 150,
                'description' => '1/2" PVC blue straight slip socket coupling for potable water lines.',
            ],
            [
                'name' => 'Blue Female Plug 1/2"',
                'sku' => 'JEM-BFPLUG-12',
                'category' => 'Plumbing',
                'brand' => 'Neltex',
                'unit' => 'piece',
                'size' => '1/2"',
                'selling_price' => 12.00,
                'cost_price' => 8.00,
                'stock' => 100,
                'description' => '1/2" PVC blue female cap/plug for temporarily or permanently closing pipe outlets.',
            ],
            [
                'name' => 'Blue Male Plug 1/2"',
                'sku' => 'JEM-BMPLUG-12',
                'category' => 'Plumbing',
                'brand' => 'Neltex',
                'unit' => 'piece',
                'size' => '1/2"',
                'selling_price' => 12.00,
                'cost_price' => 8.00,
                'stock' => 100,
                'description' => '1/2" PVC blue threaded male plug for sealing open female ports and rough-ins.',
            ],
            [
                'name' => 'Blue Coupling Reducer 1/2" × 3/4"',
                'sku' => 'JEM-BCREDUC-1234',
                'category' => 'Plumbing',
                'brand' => 'Neltex',
                'unit' => 'piece',
                'size' => '1/2" x 3/4"',
                'selling_price' => 22.00,
                'cost_price' => 15.00,
                'stock' => 100,
                'description' => '1/2" × 3/4" PVC blue reducing coupling for step-down potable waterline branches.',
            ],

            // G.I. Nipple Schedule 20
            [
                'name' => 'GI Nipple 1/2" × 2" S-20',
                'sku' => 'JEM-GINIP-20-2',
                'category' => 'Plumbing',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '1/2" x 2" S-20',
                'selling_price' => 18.00,
                'cost_price' => 12.00,
                'stock' => 100,
                'description' => 'Galvanized iron pipe nipple 1/2" diameter by 2" length Schedule 20 with threaded ends.',
            ],
            [
                'name' => 'GI Nipple 1/2" × 4" S-20',
                'sku' => 'JEM-GINIP-20-4',
                'category' => 'Plumbing',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '1/2" x 4" S-20',
                'selling_price' => 25.00,
                'cost_price' => 17.00,
                'stock' => 100,
                'description' => 'Galvanized iron pipe nipple 1/2" diameter by 4" length Schedule 20.',
            ],
            [
                'name' => 'GI Nipple 1/2" × 6" S-20',
                'sku' => 'JEM-GINIP-20-6',
                'category' => 'Plumbing',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '1/2" x 6" S-20',
                'selling_price' => 32.00,
                'cost_price' => 22.00,
                'stock' => 100,
                'description' => 'Galvanized iron pipe nipple 1/2" diameter by 6" length Schedule 20.',
            ],
            [
                'name' => 'GI Nipple 1/2" × 8" S-20',
                'sku' => 'JEM-GINIP-20-8',
                'category' => 'Plumbing',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '1/2" x 8" S-20',
                'selling_price' => 40.00,
                'cost_price' => 28.00,
                'stock' => 80,
                'description' => 'Galvanized iron pipe nipple 1/2" diameter by 8" length Schedule 20.',
            ],
            [
                'name' => 'GI Nipple 1/2" × 10" S-20',
                'sku' => 'JEM-GINIP-20-10',
                'category' => 'Plumbing',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '1/2" x 10" S-20',
                'selling_price' => 48.00,
                'cost_price' => 34.00,
                'stock' => 80,
                'description' => 'Galvanized iron pipe nipple 1/2" diameter by 10" length Schedule 20.',
            ],
            [
                'name' => 'GI Nipple 1/2" × 12" S-20',
                'sku' => 'JEM-GINIP-20-12',
                'category' => 'Plumbing',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '1/2" x 12" S-20',
                'selling_price' => 56.00,
                'cost_price' => 40.00,
                'stock' => 80,
                'description' => 'Galvanized iron pipe nipple 1/2" diameter by 12" length Schedule 20.',
            ],

            // ==========================================
            // SHEET 4: G.I. NIPPLE S-40, HOSE CLAMP, ROPE, CUP HOOK
            // ==========================================
            [
                'name' => 'GI Nipple 1/2" × 2" S-40',
                'sku' => 'JEM-GINIP-40-2',
                'category' => 'Plumbing',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '1/2" x 2" S-40',
                'selling_price' => 24.00,
                'cost_price' => 16.00,
                'stock' => 100,
                'description' => 'Heavy-gauge galvanized iron nipple 1/2" x 2" Schedule 40 for high pressure water lines.',
            ],
            [
                'name' => 'GI Nipple 1/2" × 4" S-40',
                'sku' => 'JEM-GINIP-40-4',
                'category' => 'Plumbing',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '1/2" x 4" S-40',
                'selling_price' => 34.00,
                'cost_price' => 23.00,
                'stock' => 100,
                'description' => 'Heavy-gauge galvanized iron nipple 1/2" x 4" Schedule 40.',
            ],
            [
                'name' => 'GI Nipple 1/2" × 6" S-40',
                'sku' => 'JEM-GINIP-40-6',
                'category' => 'Plumbing',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '1/2" x 6" S-40',
                'selling_price' => 44.00,
                'cost_price' => 30.00,
                'stock' => 100,
                'description' => 'Heavy-gauge galvanized iron nipple 1/2" x 6" Schedule 40.',
            ],
            [
                'name' => 'GI Nipple 1/2" × 8" S-40',
                'sku' => 'JEM-GINIP-40-8',
                'category' => 'Plumbing',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '1/2" x 8" S-40',
                'selling_price' => 54.00,
                'cost_price' => 38.00,
                'stock' => 80,
                'description' => 'Heavy-gauge galvanized iron nipple 1/2" x 8" Schedule 40.',
            ],
            [
                'name' => 'GI Nipple 1/2" × 10" S-40',
                'sku' => 'JEM-GINIP-40-10',
                'category' => 'Plumbing',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '1/2" x 10" S-40',
                'selling_price' => 65.00,
                'cost_price' => 45.00,
                'stock' => 80,
                'description' => 'Heavy-gauge galvanized iron nipple 1/2" x 10" Schedule 40.',
            ],
            [
                'name' => 'GI Nipple 1/2" × 12" S-40',
                'sku' => 'JEM-GINIP-40-12',
                'category' => 'Plumbing',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '1/2" x 12" S-40',
                'selling_price' => 75.00,
                'cost_price' => 52.00,
                'stock' => 80,
                'description' => 'Heavy-gauge galvanized iron nipple 1/2" x 12" Schedule 40.',
            ],

            // Hose Clamps
            [
                'name' => 'Hose Clamp 1/2"',
                'sku' => 'JEM-HCLP-12',
                'category' => 'Fasteners & Screws',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '1/2"',
                'selling_price' => 15.00,
                'cost_price' => 9.00,
                'stock' => 150,
                'description' => 'Stainless steel adjustable worm-drive hose clamp 1/2" for garden and compressor hoses.',
            ],
            [
                'name' => 'Hose Clamp 3/4"',
                'sku' => 'JEM-HCLP-34',
                'category' => 'Fasteners & Screws',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '3/4"',
                'selling_price' => 18.00,
                'cost_price' => 11.00,
                'stock' => 150,
                'description' => 'Stainless steel adjustable hose clamp 3/4".',
            ],
            [
                'name' => 'Hose Clamp 1"',
                'sku' => 'JEM-HCLP-10',
                'category' => 'Fasteners & Screws',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '1"',
                'selling_price' => 20.00,
                'cost_price' => 12.00,
                'stock' => 150,
                'description' => 'Stainless steel adjustable hose clamp 1".',
            ],
            [
                'name' => 'Hose Clamp 1-1/4"',
                'sku' => 'JEM-HCLP-114',
                'category' => 'Fasteners & Screws',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '1-1/4"',
                'selling_price' => 22.00,
                'cost_price' => 14.00,
                'stock' => 120,
                'description' => 'Stainless steel adjustable hose clamp 1-1/4".',
            ],
            [
                'name' => 'Hose Clamp 1-1/2"',
                'sku' => 'JEM-HCLP-112',
                'category' => 'Fasteners & Screws',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '1-1/2"',
                'selling_price' => 25.00,
                'cost_price' => 16.00,
                'stock' => 120,
                'description' => 'Stainless steel adjustable hose clamp 1-1/2".',
            ],
            [
                'name' => 'Hose Clamp 2"',
                'sku' => 'JEM-HCLP-20',
                'category' => 'Fasteners & Screws',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '2"',
                'selling_price' => 30.00,
                'cost_price' => 19.00,
                'stock' => 100,
                'description' => 'Stainless steel adjustable hose clamp 2" for drainage and pump discharge tubes.',
            ],
            [
                'name' => 'Hose Clamp 3"',
                'sku' => 'JEM-HCLP-30',
                'category' => 'Fasteners & Screws',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '3"',
                'selling_price' => 40.00,
                'cost_price' => 26.00,
                'stock' => 80,
                'description' => 'Heavy-duty adjustable hose clamp 3".',
            ],
            [
                'name' => 'Hose Clamp 4"',
                'sku' => 'JEM-HCLP-40',
                'category' => 'Fasteners & Screws',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '4"',
                'selling_price' => 50.00,
                'cost_price' => 32.00,
                'stock' => 80,
                'description' => 'Heavy-duty adjustable hose clamp 4" for industrial ducting and hoses.',
            ],
            [
                'name' => 'Hose Clamp 5"',
                'sku' => 'JEM-HCLP-50',
                'category' => 'Fasteners & Screws',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '5"',
                'selling_price' => 60.00,
                'cost_price' => 39.00,
                'stock' => 60,
                'description' => 'Industrial adjustable hose clamp 5".',
            ],
            [
                'name' => 'Hose Clamp 6"',
                'sku' => 'JEM-HCLP-60',
                'category' => 'Fasteners & Screws',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '6"',
                'selling_price' => 75.00,
                'cost_price' => 48.00,
                'stock' => 60,
                'description' => 'Large diameter industrial hose clamp 6".',
            ],

            // Poly Ropes
            [
                'name' => 'Poly Rope 2mm',
                'sku' => 'JEM-ROPE-2MM',
                'category' => 'Hardware & Accessories',
                'brand' => 'Generic',
                'unit' => 'meter',
                'size' => '2mm',
                'selling_price' => 5.00,
                'cost_price' => 3.00,
                'stock' => 300,
                'description' => 'High-tensile polypropylene 2mm rope (tali) sold per meter or whole roll (₱250). Weather and water resistant.',
            ],
            [
                'name' => 'Poly Rope 4mm',
                'sku' => 'JEM-ROPE-4MM',
                'category' => 'Hardware & Accessories',
                'brand' => 'Generic',
                'unit' => 'meter',
                'size' => '4mm',
                'selling_price' => 8.00,
                'cost_price' => 5.00,
                'stock' => 300,
                'description' => '4mm Polypropylene utility rope sold per meter or whole roll (₱450).',
            ],
            [
                'name' => 'Poly Rope 6mm',
                'sku' => 'JEM-ROPE-6MM',
                'category' => 'Hardware & Accessories',
                'brand' => 'Generic',
                'unit' => 'meter',
                'size' => '6mm',
                'selling_price' => 14.00,
                'cost_price' => 9.00,
                'stock' => 250,
                'description' => '6mm Polypropylene multi-purpose rope sold per meter or whole roll (₱750).',
            ],
            [
                'name' => 'Poly Rope 10mm',
                'sku' => 'JEM-ROPE-10MM',
                'category' => 'Hardware & Accessories',
                'brand' => 'Generic',
                'unit' => 'meter',
                'size' => '10mm',
                'selling_price' => 25.00,
                'cost_price' => 16.00,
                'stock' => 200,
                'description' => '10mm Heavy-duty poly rope for tie-downs, rigging, and trucking. Sold per meter or roll (₱1,400).',
            ],
            [
                'name' => 'Poly Rope 12mm',
                'sku' => 'JEM-ROPE-12MM',
                'category' => 'Hardware & Accessories',
                'brand' => 'Generic',
                'unit' => 'meter',
                'size' => '12mm',
                'selling_price' => 35.00,
                'cost_price' => 23.00,
                'stock' => 200,
                'description' => '12mm Industrial grade poly rope. Sold per meter or roll (₱1,950).',
            ],
            [
                'name' => 'Poly Rope 14mm',
                'sku' => 'JEM-ROPE-14MM',
                'category' => 'Hardware & Accessories',
                'brand' => 'Generic',
                'unit' => 'meter',
                'size' => '14mm',
                'selling_price' => 45.00,
                'cost_price' => 30.00,
                'stock' => 150,
                'description' => '14mm Heavy-duty rigging poly rope. Sold per meter or roll (₱2,500).',
            ],
            [
                'name' => 'Poly Rope 16mm',
                'sku' => 'JEM-ROPE-16MM',
                'category' => 'Hardware & Accessories',
                'brand' => 'Generic',
                'unit' => 'meter',
                'size' => '16mm',
                'selling_price' => 55.00,
                'cost_price' => 36.00,
                'stock' => 150,
                'description' => '16mm Thick contractor grade towing and safety rope. Sold per meter or roll (₱3,100).',
            ],
            [
                'name' => 'Poly Rope 19mm',
                'sku' => 'JEM-ROPE-19MM',
                'category' => 'Hardware & Accessories',
                'brand' => 'Generic',
                'unit' => 'meter',
                'size' => '19mm',
                'selling_price' => 70.00,
                'cost_price' => 46.00,
                'stock' => 120,
                'description' => '19mm Extra-strength poly rope. Sold per meter or roll (₱3,900).',
            ],
            [
                'name' => 'Poly Rope 22mm',
                'sku' => 'JEM-ROPE-22MM',
                'category' => 'Hardware & Accessories',
                'brand' => 'Generic',
                'unit' => 'meter',
                'size' => '22mm',
                'selling_price' => 85.00,
                'cost_price' => 56.00,
                'stock' => 100,
                'description' => '22mm Maximum capacity heavy rigging rope. Sold per meter or roll (₱4,800).',
            ],

            // Cup Hooks
            [
                'name' => 'Cup Hook 3/4"',
                'sku' => 'JEM-CHOOK-34',
                'category' => 'Fasteners & Screws',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '3/4"',
                'selling_price' => 3.00,
                'cost_price' => 1.50,
                'stock' => 300,
                'description' => '3/4" Brass-plated screw-in cup hook for ceiling hanging, kitchen organizer, and wiring guide.',
            ],
            [
                'name' => 'Cup Hook 7/8"',
                'sku' => 'JEM-CHOOK-78',
                'category' => 'Fasteners & Screws',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '7/8"',
                'selling_price' => 4.00,
                'cost_price' => 2.00,
                'stock' => 300,
                'description' => '7/8" Screw-in cup hook.',
            ],
            [
                'name' => 'Cup Hook 1"',
                'sku' => 'JEM-CHOOK-10',
                'category' => 'Fasteners & Screws',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '1"',
                'selling_price' => 5.00,
                'cost_price' => 2.50,
                'stock' => 250,
                'description' => '1" Standard metal cup hook with wood screw thread.',
            ],
            [
                'name' => 'Cup Hook 1-1/4"',
                'sku' => 'JEM-CHOOK-114',
                'category' => 'Fasteners & Screws',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '1-1/4"',
                'selling_price' => 6.00,
                'cost_price' => 3.00,
                'stock' => 200,
                'description' => '1-1/4" Medium heavy cup hook.',
            ],
            [
                'name' => 'Cup Hook 2"',
                'sku' => 'JEM-CHOOK-20',
                'category' => 'Fasteners & Screws',
                'brand' => 'Generic',
                'unit' => 'piece',
                'size' => '2"',
                'selling_price' => 8.00,
                'cost_price' => 4.00,
                'stock' => 200,
                'description' => '2" Large heavy cup hook for cords and tools.',
            ],

            // ==========================================
            // SHEET 5: PVC SANITARY FITTINGS, TILE TRIM, TRAPAL
            // ==========================================
            [
                'name' => 'PVC Sanitary Coupling 2"',
                'sku' => 'JEM-SAN-COUP-2',
                'category' => 'Plumbing',
                'brand' => 'Neltex',
                'unit' => 'piece',
                'size' => '2"',
                'selling_price' => 18.00,
                'cost_price' => 12.00,
                'stock' => 120,
                'description' => '2" Orange PVC sanitary pipe coupling with solvent-weld hub for drainage and waste lines.',
            ],
            [
                'name' => 'PVC Sanitary Coupling 3"',
                'sku' => 'JEM-SAN-COUP-3',
                'category' => 'Plumbing',
                'brand' => 'Neltex',
                'unit' => 'piece',
                'size' => '3"',
                'selling_price' => 25.00,
                'cost_price' => 16.00,
                'stock' => 100,
                'description' => '3" Orange PVC sanitary pipe coupling for main stack and soil lines.',
            ],
            [
                'name' => 'PVC Sanitary Coupling 4"',
                'sku' => 'JEM-SAN-COUP-4',
                'category' => 'Plumbing',
                'brand' => 'Neltex',
                'unit' => 'piece',
                'size' => '4"',
                'selling_price' => 35.00,
                'cost_price' => 23.00,
                'stock' => 100,
                'description' => '4" Orange PVC sanitary pipe coupling for 4-inch septic and sewer lines.',
            ],
            [
                'name' => 'PVC Sanitary P-Trap 2"',
                'sku' => 'JEM-SAN-PTRAP-2',
                'category' => 'Plumbing',
                'brand' => 'Neltex',
                'unit' => 'piece',
                'size' => '2"',
                'selling_price' => 65.00,
                'cost_price' => 45.00,
                'stock' => 80,
                'description' => '2" PVC sanitary P-Trap with cleanout plug to prevent sewer gas backflow in floor drains and sinks.',
            ],
            [
                'name' => 'PVC Sanitary P-Trap 3"',
                'sku' => 'JEM-SAN-PTRAP-3',
                'category' => 'Plumbing',
                'brand' => 'Neltex',
                'unit' => 'piece',
                'size' => '3"',
                'selling_price' => 95.00,
                'cost_price' => 65.00,
                'stock' => 60,
                'description' => '3" PVC sanitary P-Trap for commercial drainage and wash areas.',
            ],
            [
                'name' => 'PVC Sanitary P-Trap 4"',
                'sku' => 'JEM-SAN-PTRAP-4',
                'category' => 'Plumbing',
                'brand' => 'Neltex',
                'unit' => 'piece',
                'size' => '4"',
                'selling_price' => 135.00,
                'cost_price' => 92.00,
                'stock' => 50,
                'description' => '4" Heavy-duty PVC sanitary P-Trap for main building sewer exits.',
            ],
            [
                'name' => 'PVC Sanitary Wye 2"',
                'sku' => 'JEM-SAN-WYE-2',
                'category' => 'Plumbing',
                'brand' => 'Neltex',
                'unit' => 'piece',
                'size' => '2"',
                'selling_price' => 30.00,
                'cost_price' => 20.00,
                'stock' => 100,
                'description' => '2" PVC 45-degree sanitary wye fitting for smooth flow direction transitions in drains.',
            ],
            [
                'name' => 'PVC Sanitary Wye 3"',
                'sku' => 'JEM-SAN-WYE-3',
                'category' => 'Plumbing',
                'brand' => 'Neltex',
                'unit' => 'piece',
                'size' => '3"',
                'selling_price' => 50.00,
                'cost_price' => 34.00,
                'stock' => 80,
                'description' => '3" PVC 45-degree sanitary wye fitting.',
            ],
            [
                'name' => 'PVC Sanitary Wye 4"',
                'sku' => 'JEM-SAN-WYE-4',
                'category' => 'Plumbing',
                'brand' => 'Neltex',
                'unit' => 'piece',
                'size' => '4"',
                'selling_price' => 85.00,
                'cost_price' => 58.00,
                'stock' => 60,
                'description' => '4" PVC 45-degree sanitary wye fitting for main sewer line branches.',
            ],
            [
                'name' => 'PVC Sanitary Wye Reducer 3" × 2"',
                'sku' => 'JEM-SAN-WYERED-32',
                'category' => 'Plumbing',
                'brand' => 'Neltex',
                'unit' => 'piece',
                'size' => '3" x 2"',
                'selling_price' => 55.00,
                'cost_price' => 37.00,
                'stock' => 80,
                'description' => '3" × 2" PVC sanitary reducing wye for joining a 2" branch pipe into a 3" main run.',
            ],
            [
                'name' => 'PVC Sanitary Wye Reducer 4" × 2"',
                'sku' => 'JEM-SAN-WYERED-42',
                'category' => 'Plumbing',
                'brand' => 'Neltex',
                'unit' => 'piece',
                'size' => '4" x 2"',
                'selling_price' => 65.00,
                'cost_price' => 44.00,
                'stock' => 70,
                'description' => '4" × 2" PVC sanitary reducing wye for connecting sink/drain lines to main sewer stack.',
            ],
            [
                'name' => 'PVC Sanitary Wye Reducer 4" × 3"',
                'sku' => 'JEM-SAN-WYERED-43',
                'category' => 'Plumbing',
                'brand' => 'Neltex',
                'unit' => 'piece',
                'size' => '4" x 3"',
                'selling_price' => 75.00,
                'cost_price' => 50.00,
                'stock' => 70,
                'description' => '4" × 3" PVC sanitary reducing wye for branch connections in commercial drainage systems.',
            ],
            [
                'name' => 'Tile Trim Aluminum 8ft',
                'sku' => 'JEM-TRIM-ALUM',
                'category' => 'Paint & Finishes',
                'brand' => 'Generic',
                'unit' => 'length',
                'size' => '8ft',
                'selling_price' => 175.00,
                'cost_price' => 120.00,
                'stock' => 80,
                'description' => '8-foot Premium extruded aluminum tile edge trim for protective and elegant ceramic wall & floor corners.',
            ],
            [
                'name' => 'Tile Trim White 8ft',
                'sku' => 'JEM-TRIM-WHT',
                'category' => 'Paint & Finishes',
                'brand' => 'Generic',
                'unit' => 'length',
                'size' => '8ft',
                'selling_price' => 65.00,
                'cost_price' => 42.00,
                'stock' => 120,
                'description' => '8-foot PVC white tile trim corner moulding for bathroom and kitchen tiles.',
            ],
            [
                'name' => 'Tile Trim Brown 8ft',
                'sku' => 'JEM-TRIM-BRN',
                'category' => 'Paint & Finishes',
                'brand' => 'Generic',
                'unit' => 'length',
                'size' => '8ft',
                'selling_price' => 65.00,
                'cost_price' => 42.00,
                'stock' => 100,
                'description' => '8-foot PVC brown woodgrain tile trim corner moulding.',
            ],
            [
                'name' => 'Tile Trim Beige 8ft',
                'sku' => 'JEM-TRIM-BGE',
                'category' => 'Paint & Finishes',
                'brand' => 'Generic',
                'unit' => 'length',
                'size' => '8ft',
                'selling_price' => 65.00,
                'cost_price' => 42.00,
                'stock' => 100,
                'description' => '8-foot PVC beige tile trim corner moulding for granite and ceramic tile edges.',
            ],
            [
                'name' => 'Trapal Baga Heavy Duty',
                'sku' => 'JEM-TRAPAL-BAGA',
                'category' => 'Tarpaulin & Covers',
                'brand' => 'Generic',
                'unit' => 'meter',
                'size' => 'Heavy Duty',
                'selling_price' => 85.00,
                'cost_price' => 58.00,
                'stock' => 150,
                'description' => 'Trapal baga thick heavy-duty waterproof laminated tarpaulin sheet for truck hauling, roofs, and temporary shelter.',
            ],
            [
                'name' => 'Trapal Nipis Light Duty',
                'sku' => 'JEM-TRAPAL-NIPIS',
                'category' => 'Tarpaulin & Covers',
                'brand' => 'Generic',
                'unit' => 'meter',
                'size' => 'Light Duty',
                'selling_price' => 75.00,
                'cost_price' => 50.00,
                'stock' => 150,
                'description' => 'Trapal nipis flexible light-duty waterproof blue/silver tarpaulin cover for painting and cargo protection.',
            ],
        ];

        // 6. Insert All Products, Variants, and Batches
        $batchCounter = 1;
        foreach ($items as $item) {
            $catId = $categories[$item['category']]->id ?? $categories['Lumber']->id;
            $brandId = $brands[$item['brand']]->id ?? $brands['Generic']->id;

            $product = Product::create([
                'category_id' => $catId,
                'brand_id' => $brandId,
                'name' => $item['name'],
                'description' => $item['description'],
                'base_price' => $item['selling_price'],
                'cost_price' => $item['cost_price'],
                'selling_price' => $item['selling_price'],
                'unit' => $item['unit'],
                'stock_quantity' => $item['stock'],
                'low_stock_threshold' => 10,
                'status' => 'active',
            ]);

            // Create variant
            ProductVariant::create([
                'product_id' => $product->id,
                'sku' => $item['sku'],
                'size' => $item['size'],
                'price' => $item['selling_price'],
                'stock_quantity' => $item['stock'],
                'status' => 'active',
            ]);

            // Create batch for full traceability
            if (Schema::hasTable('inventory_batches')) {
                $batchNumber = 'BATCH-' . date('Y') . '-' . str_pad($batchCounter++, 4, '0', STR_PAD_LEFT);
                InventoryBatch::create([
                    'product_id' => $product->id,
                    'batch_number' => $batchNumber,
                    'supplier_id' => $supplier ? $supplier->id : null,
                    'supplier_name' => $supplier ? $supplier->name : 'JEM Hardware Direct',
                    'cost_price' => $item['cost_price'],
                    'selling_price' => $item['selling_price'],
                    'initial_quantity' => $item['stock'],
                    'quantity' => $item['stock'],
                    'received_date' => now()->subDays(rand(1, 15))->toDateString(),
                    'status' => 'active',
                    'notes' => 'Transcribed directly from physical inventory sheets',
                ]);
            }
        }
    }
}
