import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, ClipboardList, Clock3, FileEdit, LayoutDashboard, LogOut, Package, Plus, Receipt, Search, ShoppingCart, Star, Truck, X } from 'lucide-react'
import { createOrderAdjustment, createPosCheckout, createStaffRestockRequest, getLowStock, getNotifications, getProducts, getStaffFeedback, getStaffOrders, getStaffRestockRequests, markNotificationRead, updateStaffOrderStatus } from '../../api'
import '../../staff.css'

const fallbackProducts = [
  { id: 1, name: 'Coco Lumber 2 x 3 x 10 ft', stock_quantity: 18, unit: 'piece', base_price: 185 },
  { id: 2, name: 'Portland Cement 40kg', stock_quantity: 84, unit: 'bag', base_price: 285 },
  { id: 3, name: 'Common Wire Nail 2 inch', stock_quantity: 6, unit: 'kg', base_price: 92 },
]
const nav = [['Dashboard', LayoutDashboard], ['Restock Request', ClipboardList], ['Customer Orders', ShoppingCart], ['Walk-In Order / POS', Receipt], ['Order Adjustment', FileEdit], ['Feedback', Star]]
const unwrap = (payload) => Array.isArray(payload) ? payload : payload?.data || []

function StaffStatus({ value }) { return <span className={`status status-${String(value).toLowerCase().replaceAll(' ', '-').replaceAll('_', '-')}`}>{String(value).replaceAll('_', ' ')}</span> }
function StaffPanel({ title, subtitle, children, action }) { return <section className="panel staff-panel"><div className="panel-head"><div><h2>{title}</h2>{subtitle && <p className="muted">{subtitle}</p>}</div>{action}</div>{children}</section> }

export default function StaffModule({ onLogout }) {
  const [active, setActive] = useState('Dashboard')
  const [collapsed, setCollapsed] = useState(false)
  const [orders, setOrders] = useState([])
  const [products, setProducts] = useState([])
  const [lowStock, setLowStock] = useState([])
  const [requests, setRequests] = useState([])
  const [feedback, setFeedback] = useState([])
  const [notifications, setNotifications] = useState([])
  const [showNotifications, setShowNotifications] = useState(false)
  const [notice, setNotice] = useState('')
  const refresh = async () => {
    const results = await Promise.allSettled([getStaffOrders(), getProducts({ per_page: 100 }), getLowStock(), getStaffRestockRequests(), getStaffFeedback(), getNotifications()])
    const read = (index) => results[index].status === 'fulfilled' ? results[index].value : []
    setOrders(unwrap(read(0))); setProducts(unwrap(read(1))); setLowStock(unwrap(read(2))); setRequests(unwrap(read(3))); setFeedback(unwrap(read(4)))
    setNotifications(unwrap(read(5)))
  }
  useEffect(() => { refresh() }, [])
  const notify = (message) => { setNotice(message); window.setTimeout(() => setNotice(''), 3500) }
  const content = active === 'Dashboard' ? <StaffDashboard orders={orders} lowStock={lowStock} requests={requests} onNavigate={setActive} /> : active === 'Restock Request' ? <RestockPanel products={products.length ? products : fallbackProducts} requests={requests} onDone={(message) => { notify(message); refresh() }} /> : active === 'Customer Orders' ? <OrdersPanel orders={orders} onDone={(message) => { notify(message); refresh() }} /> : active === 'Walk-In Order / POS' ? <PosPanel products={products.length ? products : fallbackProducts} onDone={(message) => { notify(message); refresh() }} /> : active === 'Order Adjustment' ? <AdjustmentPanel orders={orders} products={products.length ? products : fallbackProducts} onDone={(message) => { notify(message); refresh() }} /> : <FeedbackPanel feedback={feedback} />
  const unread = notifications.filter((item) => !item.read).length
  const readNotification = async (item) => { if (!item.read) { try { await markNotificationRead(item.id); setNotifications((current) => current.map((notification) => notification.id === item.id ? { ...notification, read: true } : notification)) } catch { /* Keep the notification visible if the API is temporarily unavailable. */ } } }
  return <div className="staff-workspace"><aside className={`staff-sidebar ${collapsed ? 'collapsed' : ''}`}><div className="staff-brand"><div className="brand-mark">J</div><div><strong>JEM Hardware</strong><small>Staff operations</small></div></div><div className="staff-role">STAFF ACCOUNT</div><nav>{nav.map(([label, Icon]) => <button key={label} className={active === label ? 'staff-nav active' : 'staff-nav'} onClick={() => setActive(label)}><Icon size={18} /><span>{label}</span>{label === 'Restock Request' && requests.filter((item) => item.status === 'pending').length > 0 && <b>{requests.filter((item) => item.status === 'pending').length}</b>}</button>)}</nav><div className="staff-bottom"><button className="staff-nav" onClick={onLogout}><LogOut size={18} /><span>Logout</span></button></div></aside><main className="staff-main"><header className="staff-topbar"><button className="icon-button" onClick={() => setCollapsed((value) => !value)} title="Toggle sidebar"><span aria-hidden="true">☰</span></button><div><span>JEM Hardware</span><strong>/ {active}</strong></div><div className="staff-user"><button className="notification-button" onClick={() => setShowNotifications((value) => !value)} title="Notifications">🔔{unread > 0 && <b>{unread}</b>}</button><span className="staff-dot" /> Online · Staff</div>{showNotifications && <div className="notification-menu"><strong>Notifications</strong>{notifications.slice(0, 6).map((item) => <button className={item.read ? 'notification-item read' : 'notification-item'} key={item.id} onClick={() => readNotification(item)}><span>{item.data?.message || item.type || 'Staff notification'}</span><small>{new Date(item.created_at).toLocaleString()}</small></button>)}{!notifications.length && <span className="notification-empty">No notifications yet.</span>}</div>}</header>{notice && <div className="staff-toast">{notice}</div>}<div className={`staff-content ${active === 'Walk-In Order / POS' ? 'staff-pos-content' : ''}`}>{content}</div></main></div>
}

function StaffDashboard({ orders, lowStock, requests, onNavigate }) {
  const counts = { pending: orders.filter((order) => ['pending', 'confirmed'].includes(order.status)).length, processing: orders.filter((order) => order.status === 'processing').length, ready: orders.filter((order) => order.status === 'ready').length, completed: orders.filter((order) => ['completed', 'delivered'].includes(order.status)).length }
  return <><div className="staff-page-heading"><div><p className="eyebrow">Daily operations</p><h1>Good morning, team.</h1><p className="muted">Keep customer orders and store movement on track.</p></div><button className="button button-accent" onClick={() => onNavigate('Walk-In Order / POS')}><Plus size={16} /> New walk-in order</button></div><div className="staff-metrics"><StaffMetric icon={Clock3} label="Pending orders" value={counts.pending} tone="orange" /><StaffMetric icon={Package} label="Orders to process" value={counts.processing} tone="blue" /><StaffMetric icon={Truck} label="Ready orders" value={counts.ready} tone="green" /><StaffMetric icon={Receipt} label="Completed orders" value={counts.completed} tone="slate" /><StaffMetric icon={ClipboardList} label="Pending restock" value={requests.filter((item) => item.status === 'pending').length} tone="orange" /><StaffMetric icon={AlertTriangle} label="Low-stock products" value={lowStock.length} tone="red" /></div><div className="staff-grid"><StaffPanel title="Recent orders" subtitle="Orders requiring operational attention" action={<button className="link-button" onClick={() => onNavigate('Customer Orders')}>View all</button>}><div className="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Payment</th><th>Status</th></tr></thead><tbody>{orders.slice(0, 5).map((order) => <tr key={order.id}><td><strong>{order.order_number || `#${order.id}`}</strong><small>{new Date(order.created_at).toLocaleDateString()}</small></td><td>{order.customer?.user?.name || 'Customer'}</td><td><strong>₱{Number(order.total || 0).toLocaleString()}</strong></td><td>{order.payment_method || 'COD'}</td><td><StaffStatus value={order.status} /></td></tr>)}</tbody></table></div>{!orders.length && <StaffEmpty text="No customer orders have been placed yet." />}</StaffPanel><StaffPanel title="Low-stock products" subtitle="Review before the next customer order"><div className="staff-stock-list">{lowStock.slice(0, 6).map((item) => <div className="staff-stock-row" key={`${item.type}-${item.id}`}><div className="product-thumb nails">!</div><div><strong>{item.name || item.sku}</strong><span>{item.stock} available · minimum {item.threshold}</span></div><StaffStatus value={item.status} /></div>)}</div>{!lowStock.length && <StaffEmpty text="Inventory levels are healthy." />}</StaffPanel></div></>
}
function StaffMetric({ icon: Icon, label, value, tone }) { return <div className="staff-metric"><div className={`metric-icon ${tone}`}><Icon size={18} /></div><div><span>{label}</span><strong>{value}</strong></div></div> }
function StaffEmpty({ text }) { return <div className="staff-empty">{text}</div> }

function RestockPanel({ products, requests, onDone }) {
  const [form, setForm] = useState({ product_id: '', requested_quantity: '', notes: '' }); const selected = products.find((product) => String(product.id) === form.product_id)
  const submit = async (event) => { event.preventDefault(); if (!selected || Number(form.requested_quantity) < 1 || !form.notes.trim()) return; try { await createStaffRestockRequest({ ...form, product_id: Number(form.product_id), requested_quantity: Number(form.requested_quantity) }); setForm({ product_id: '', requested_quantity: '', notes: '' }); onDone('Restock request submitted for administrator review.') } catch (error) { onDone(error.message) } }
  return <div className="staff-page"><StaffHeading eyebrow="Inventory support" title="Restock request" subtitle="Flag products that need replenishment before they interrupt an order." /><div className="staff-two-col"><StaffPanel title="Submit a request" subtitle="All requests start as Pending"><form className="staff-form" onSubmit={submit}><label>Product<select className="input" required value={form.product_id} onChange={(event) => setForm({ ...form, product_id: event.target.value })}><option value="">Select a product</option>{products.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select></label>{selected && <div className="stock-callout"><strong>{selected.stock_quantity ?? selected.stock ?? 0} {selected.unit || 'unit'} available</strong><span>Current stock for {selected.name}</span></div>}<label>Requested quantity<input className="input" type="number" min="1" required value={form.requested_quantity} onChange={(event) => setForm({ ...form, requested_quantity: event.target.value })} /></label><label>Reason<textarea className="input" rows="4" required value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} placeholder="Explain why this product needs replenishment" /></label><button className="button button-accent" type="submit"><ClipboardList size={16} /> Submit restock request</button></form></StaffPanel><StaffPanel title="Request history" subtitle="Your submitted requests"><div className="table-wrap"><table><thead><tr><th>Request</th><th>Product</th><th>Quantity</th><th>Date</th><th>Status</th></tr></thead><tbody>{requests.map((item) => <tr key={item.id}><td>#{item.id}</td><td>{item.product?.name || 'Product'}</td><td>{item.requested_quantity}</td><td>{new Date(item.created_at).toLocaleDateString()}</td><td><StaffStatus value={item.status} /></td></tr>)}</tbody></table></div>{!requests.length && <StaffEmpty text="No restock requests yet." />}</StaffPanel></div></div>
}
function StaffHeading({ eyebrow, title, subtitle }) { return <div className="staff-page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="muted">{subtitle}</p></div></div> }

function OrdersPanel({ orders, onDone }) {
  const [query, setQuery] = useState(''); const filtered = orders.filter((order) => `${order.order_number} ${order.customer?.user?.name || ''}`.toLowerCase().includes(query.toLowerCase()))
  const action = async (order) => { const actions = { pending: ['receive', 'Receive order'], confirmed: ['receive', 'Receive order'], received: ['process', 'Process order'], processing: ['ready', 'Mark ready'], ready: ['complete', 'Complete order'], out_for_delivery: ['complete', 'Complete delivery'] }; const next = actions[order.status]; if (!next || !window.confirm(`${next[1]} for ${order.order_number}?`)) return; try { await updateStaffOrderStatus(order.id, next[0]); onDone('Order status updated.') } catch (error) { onDone(error.message) } }
  return <div className="staff-page"><StaffHeading eyebrow="Customer service" title="Customer orders" subtitle="Receive, prepare, and complete online orders." /><StaffPanel title="Order queue" subtitle="Search by order number or customer"><div className="search-box staff-search"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search order or customer" /></div><div className="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Payment</th><th>Status</th><th>Action</th></tr></thead><tbody>{filtered.map((order) => <tr key={order.id}><td><strong>{order.order_number || `#${order.id}`}</strong><small>{new Date(order.created_at).toLocaleString()}</small></td><td>{order.customer?.user?.name || 'Customer'}<small>{order.customer?.user?.phone || ''}</small></td><td><strong>₱{Number(order.total || 0).toLocaleString()}</strong></td><td>{order.payment_method || 'COD'}</td><td><StaffStatus value={order.status} /></td><td><button className="button button-dark compact" onClick={() => action(order)}>Update</button></td></tr>)}</tbody></table></div>{!filtered.length && <StaffEmpty text="No orders match this search." />}</StaffPanel></div>
}

function PosPanel({ products, onDone }) {
  const [query, setQuery] = useState(''); const [cart, setCart] = useState([]); const [payment, setPayment] = useState('cod'); const visible = products.filter((product) => product.name.toLowerCase().includes(query.toLowerCase())); const total = cart.reduce((sum, item) => sum + item.price * item.quantity, 0)
  const add = (product) => setCart((current) => { const found = current.find((item) => item.id === product.id); if (found) return current.map((item) => item.id === product.id ? { ...item, quantity: Math.min(item.quantity + 1, Number(product.stock_quantity ?? product.stock ?? 0)) } : item); return [...current, { ...product, price: Number(product.base_price || product.price || 0), quantity: 1 }] })
  const change = (id, delta) => setCart((current) => current.map((item) => item.id === id ? { ...item, quantity: Math.max(1, item.quantity + delta) } : item))
  const complete = async () => { if (!cart.length || !window.confirm('Confirm Walk-In Transaction?')) return; try { await createPosCheckout({ items: cart.map((item) => ({ product_id: item.id, quantity: item.quantity, unit_price: item.price })), payment_method: payment }); setCart([]); onDone('Walk-in transaction completed and inventory updated.') } catch (error) { onDone(error.message) } }
  return <div className="staff-page"><StaffHeading eyebrow="Store counter" title="Walk-in order / POS" subtitle="Fast, stock-aware checkout for customers in the store." /><div className="pos-layout"><StaffPanel title="Products" subtitle="Only add quantities available in stock"><div className="search-box staff-search"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search products" /></div><div className="pos-products">{visible.map((product) => <div className="pos-product" key={product.id}><div className="product-visual cement">{product.category?.name || 'Hardware'}</div><strong>{product.name}</strong><span>₱{Number(product.base_price || 0).toLocaleString()} / {product.unit || 'unit'}</span><small>{product.stock_quantity ?? product.stock ?? 0} available</small><button className="button button-accent compact" disabled={Number(product.stock_quantity ?? product.stock ?? 0) < 1} onClick={() => add(product)}><Plus size={14} /> Add</button></div>)}</div></StaffPanel><StaffPanel title="Current order" subtitle="Review before completing"><div className="pos-cart">{cart.map((item) => <div className="pos-cart-row" key={item.id}><div><strong>{item.name}</strong><span>₱{item.price.toLocaleString()} × {item.quantity}</span></div><div><button className="qty-button" onClick={() => change(item.id, -1)}>-</button><button className="qty-button" onClick={() => change(item.id, 1)}>+</button><strong>₱{(item.price * item.quantity).toLocaleString()}</strong></div></div>)}{!cart.length && <StaffEmpty text="Add products to begin a walk-in order." />}</div><div className="pos-total"><span>Total</span><strong>₱{total.toLocaleString()}</strong></div><label className="staff-payment">Payment method<select className="input" value={payment} onChange={(event) => setPayment(event.target.value)}><option value="cash">Cash</option><option value="gcash">GCash</option><option value="maya">PayMaya</option><option value="bank_transfer">Bank transfer</option></select></label><button className="button button-accent" disabled={!cart.length} onClick={complete}><Receipt size={16} /> Complete transaction</button></StaffPanel></div></div>
}

function AdjustmentPanel({ orders, products, onDone }) { const [form, setForm] = useState({ order_id: '', product_id: '', original_quantity: '', requested_quantity: '', reason: '' }); const submit = async (event) => { event.preventDefault(); try { await createOrderAdjustment({ ...form, order_id: Number(form.order_id), product_id: Number(form.product_id), original_quantity: Number(form.original_quantity), requested_quantity: Number(form.requested_quantity) }); onDone('Order adjustment submitted for administrator review.'); setForm({ order_id: '', product_id: '', original_quantity: '', requested_quantity: '', reason: '' }) } catch (error) { onDone(error.message) } }; return <div className="staff-page"><StaffHeading eyebrow="Exception handling" title="Order adjustment" subtitle="Submit a request when an order needs administrator review." /><StaffPanel title="New adjustment request"><form className="staff-form narrow" onSubmit={submit}><label>Order<select className="input" required value={form.order_id} onChange={(event) => setForm({ ...form, order_id: event.target.value })}><option value="">Select an order</option>{orders.map((order) => <option key={order.id} value={order.id}>{order.order_number || `#${order.id}`}</option>)}</select></label><label>Product<select className="input" required value={form.product_id} onChange={(event) => setForm({ ...form, product_id: event.target.value })}><option value="">Select a product</option>{products.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select></label><div className="form-row"><label>Original quantity<input className="input" type="number" min="1" required value={form.original_quantity} onChange={(event) => setForm({ ...form, original_quantity: event.target.value })} /></label><label>Requested quantity<input className="input" type="number" min="1" required value={form.requested_quantity} onChange={(event) => setForm({ ...form, requested_quantity: event.target.value })} /></label></div><label>Reason<textarea className="input" rows="4" required value={form.reason} onChange={(event) => setForm({ ...form, reason: event.target.value })} /></label><button className="button button-accent"><FileEdit size={16} /> Submit adjustment request</button></form></StaffPanel></div> }
function FeedbackPanel({ feedback }) { return <div className="staff-page"><StaffHeading eyebrow="Customer voice" title="Customer feedback" subtitle="View-only feedback for service follow-up." /><StaffPanel title="Latest feedback"><div className="feedback-list">{feedback.map((item) => <article key={item.id}><div className="feedback-stars">★★★★★</div><strong>{item.subject || 'Customer feedback'}</strong><p>{item.message}</p><small>{new Date(item.created_at).toLocaleString()}</small></article>)}</div>{!feedback.length && <StaffEmpty text="No customer feedback yet." />}</StaffPanel></div> }
